### PR TITLE
Rename TouchEffect VisualState from Normal to Unpressed for avoiding naming conflict

### LINKED ISSUE #850: [Bug] xct:TouchEffect.NativeAnimation incompatible with VisualStateManager
### Steps to Reproduce

Hi and thanks again for a great component!

I noticed that if you have a control that gets coloured via the VisualStateManager, something like this:

```xaml
<VisualStateManager.VisualStateGroups>
    <VisualStateGroup x:Name="CommonStates">
        <VisualState x:Name="Selected">
            <VisualState.Setters>
                <Setter Property="Style" Value="{StaticResource SelectedStyle}" />
            </VisualState.Setters>
        </VisualState>
        <VisualState x:Name="Normal">
            <VisualState.Setters>
                <Setter Property="Style" Value="{StaticResource NormalStyle}" />
            </VisualState.Setters>
        </VisualState>
    </VisualStateGroup>
</VisualStateManager.VisualStateGroups>
```

... where 'SelectedStyle' and 'NormalStyle' assign a background color, and you add the following to the control's root:

```xaml
xct:TouchEffect.NativeAnimation="True"
```

... then, when the control is interacted with, it never gets the 'Selected' style's background color.

I am guessing what happens is that TouchEffect samples the the color when interaction starts, and it gets executed _before_ the VisualStateManager has had a chance to change the color to 'Selected' state, so when touch is released the TouchEffect puts back the old style's colors. I haven't looked at the code but this is what it looks like.

I only tested this on iOS.

### Expected Behavior

TouchEffect should not prevent VisualStateManager from working.

### Actual Behavior

TouchEffect should prevents VisualStateManager from working.

### Basic Information

- Version with issue: 1.0.2
- Last known good version: None?
- IDE:
- Platform Target Frameworks: 
  - iOS:  14.4

### Workaround

Put the state manager higher up in the hierarchy than the TouchEffect.

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###
Rename "Normal" VisualState to "Unpressed" for avoiding naming conflict.
Unfortunately, **Normal** state's name is reserved by XF https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager

We have to change it to something different.

### Bugs Fixed ###
- Fixes #850

### API Changes ###

Changed:
TouchEffect's regular/normal VisualState name

### Behavioral Changes ###
I am not sure that a lot of people are using VisualStateManager with touch effect, but anyway, possibly something can be broken.

### PR Checklist ###
- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [X] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by pictos** [comment]
@AndreiMisiukevich somehow this can a breaking change?

**Comment by AndreiMisiukevich** [comment]
I think yes it can be

**Comment by AndreiMisiukevich** [comment]
@pictos )

**Review by pictos — APPROVED** [review]
Can we document this breaking change on the docs?

**Comment by AndreiMisiukevich** [comment]
> Can we document this breaking change on the docs?

Could you please explain what does it mean?) Should I make a separate PR somewhere?

**Pull request merged**
