### PR TITLE
ValidationGroupBehavior

### PR DESCRIPTION
**Pull request by GuidoNeele**
### Description of Change ###

A ValidationGroupBehavior to group multiple behaviors so they can be validated all at once.

### New feature ###

- PR for issue #1327 

### PR Checklist ###

- [x] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by brminnick** [comment]
Thanks @GuidoNeele!

Just curious - how come `ValidationGroupBehavior` doesn't inherit from `ValidationBehavior` (or `BaseBehavior<TView>`)? 

All of the current behaviors in Xamarin.CommunityToolkit currently inherit from `ValidationBehavior `, and, if it's possible, I'd love it for `ValidationGroupBehavior` to do the same.

If it's not possible or there's a good reason not to inherit from `BaseBehavior`, that's fine too, just let me know!

**Comment by GuidoNeele** [comment]
Hi Brandon,

Well, I was thinking about the same the past weekend and I will have a look. If the ValidationGroupBehavior would inherit from ValidationBehavior then validating groups of groups should also be possible, since the Group property would be available on ValidationGroupBehavior also. I do see the added benefit of the style and state properties so inheriting would be best. If it doesn't work out I will have a look at BaseBehavior.

**Comment by GuidoNeele** [comment]
I've simplified the `ValidationGroup` to only inherit from `BindableObject`. Inheriting from `ValidationGroup` and `BaseBehavior` didn't really make sense since we only want to group behaviors, the group itself isn't used as a behavior. I further modified the group so we can have nested validation groups. 

Validation groups can be specified in the Resources of the page like so:

```xaml
<xct:ValidationGroup x:Key="TotalValidationGroup" x:Name="TotalValidationGroup">
    <xct:ValidationGroup x:Name="ContactValidationGroup" />
    <xct:ValidationGroup x:Name="InfoValidationGroup" />
</xct:ValidationGroup>
```

The `ValidationGroup` can then be used to attach to a behavior or for example to enable an error or information message like I have done in the sample page.

What do you think?

**Comment by GuidoNeele** [comment]
Any news on this?

**Comment by brminnick** [comment]
Hey @GuidoNeele! Since this is still in discussion, and we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui), please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Pull request closed without merging**
