### PR TITLE
[Bug] [Fixed] #1712

### LINKED ISSUE #1712: [Bug] UWP PopUp LightDissmis disable not working as expected
### Description

When using a PopUp on UWP `IsLightDismissEnabled = false` won't disable lightdismiss, but only disable the propper reaction.

### Steps to Reproduce

1. Create Xamarin UWP App with PopUp
2. Disable lightdismiss `IsLightDismissEnabled = false`
3. Show Popup in App
4. Click outside Popup

### Expected Behavior
Popup won't close.

### Actual Behavior
Popup will close, but following code in an async method will never continue.
`var result = await Application.Current.MainPage.Navigation.ShowPopupAsync(popUp);`

### Basic Information

- Version with issue: 1.3.0
- Last known good version: -
- IDE: VisualStudio 2019
- Platform Target Frameworks: 
  - UWP:  19041

### Workaround

1. don't disable lightdismiss
2. add a specific returnvalue to GetLightdismissResult
3. show your popup again if closed by lightdismiss

### PR DESCRIPTION
**Pull request by rxDietel**
### Description of Bug ###

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/UWP/PopupRenderer.uwp.cs
Call OnClosing even if no LightDismiss enabled
OnClosing won't let the PopUp close if the Close wasn't triggered by dismiss.

### Issues Fixed ###

- Fixes #1712

### Annotations ###
Documentation: Created issue that documentation for Popup is missing
Tests: No test created, Change is only in the reaction of the UWP UI

### PR Checklist ###
- [x] Has a linked Issue, and the Issue has been `approved`
- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard
- [x] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by brminnick** [comment]
Thanks! Could you add Unit Tests and a reproduction in the Sample App?

**Comment by rxDietel** [comment]
Just modified the already existing Sample for the light dismiss Popup in the project.
I can't find a usefull thing to unittest the popup, because it would need a UI Test to confirm the changes.

**Comment by bijington** [comment]
this is on my queue to review I just need to fix my VM to checkout the code and confirm it

**Review by bijington — APPROVED** [review]
Looks good to me! Thank you for this

**Pull request merged**
