### PR TITLE
Better MediaElement error handling

### LINKED ISSUE #399: [Bug] MediaElement not raising MediaFailed event on Android when given a URL and device has no network
### Description
MediaElement displays a blank screen on Android when the device is in flight mode. On UWP, when it fails to load the native control displays a message saying it cannot play back the media. Hooking into the MediaFailed event allows me to provide a custom message on top of that. This doesn't work on Android (nor iOS) since the MediaFailed event is never triggered.

### Steps to Reproduce

1. Set device to flight mode
2. Set MediaElement source with a URL and AutoPlay enabled
3. MediaElement is blank with no information on what is happening

### Expected Behavior
MediaFailed event should be triggered in the first instance to allow custom messaging.

### Actual Behavior
MediaFailed event does not get triggered.

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 10.1
- Android Support Library Version: 28.0.0.3
- Nuget Packages: v1.1.0 of Xamarin.AndroidX.MediaRouter

### LINKED ISSUE #1592: [Bug] MediaElement throws an internal error when it fails to load the media with a Java.Lang.RuntimeException: 'setDataSource failed: status = 0x80000000'
### Description
When MediaElement fails to load a video from url (either because the url does not point to a video, or because it timed out), it throws an internal error, crashing the app. This does not trigger the MediaFailed event.

### Steps to Reproduce

1. Download the repro from the Java.Lang.RuntimeException branch
2. Click the open video button
3. Wait for the crash

### Expected Behavior
Exception resolved internally and MediaFailed event triggered

### Actual Behavior
Internal exception thrown, crashing the app

### Basic Information

    Version with issue: 1.2.0

    IDE: Visual Studio Community 2019

    Platform Target Frameworks:
        iOS: Xamarin default
        Android: 11.0

    Nuget Packages:
    NETStandard.Library
    Xamarin.CommunityToolkit
    Xamarin.Essentials
    Xamarin.Forms

    Affected Devices:
    Motorola One 5G Ace - Android 10

### Reproduction Link

https://github.com/NickCRowork/VideoViewError/tree/Java.Lang.RuntimeException

### PR DESCRIPTION
**Pull request by anvuks**
### Description of Bug ###

When `MediaMetadataRetriever` fails to load online video metadata, because the video doesn't exist or it times out due to a connection error, it throws IllegalArgumentException. I've just wrapped the problematic method call with a try/catch that raises `MetadataRetrievalFailed` event.

When the event is raised, `MediaElementRenderer` stops the video playback, sets the state to `MediaElementState.Closed`, and raises OnMediaFailed in the shared code. The same implementation applies if the video itself fails to load or play to the end (native implementation details). If both of them try to call `OnError()`, only one can succeed, until the next media source update. This is so we can avoid calling `OnMediaFailed` more than once for the same source, which would be expected behavior.

### Issues Fixed ###

- Fixes #1592
- Fixes #399

### PR Checklist ###

- [x] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by brettnguyen** [comment]
can someone please push this my app is completely broken now

**Comment by brettnguyen** [comment]
@pictos

**Comment by pictos** [comment]
@anvuks I can't deploy the sample app on your branch, it closes right after launches. The `main` branch works. Can you double check that, please?

**Comment by anvuks** [comment]
@pictos I just tried it and you are right, the app closes right after it opens, only it happened on the main branch for me... The issue seems to be in the android linker settings, you should set it to `None` instead of `Sdk assemblies only`. I think there is no benefit in linking debug builds, it just slows everything down.

**Comment by pictos** [comment]
@anvuks can you rebase your code against main? Not sure if there's any update but just to make sure... Sadly I can't merge this with the issue, because that can break the package and other users somehow.

**Comment by anvuks** [comment]
@pictos I just checked and my branch is up to date with main. Can you try cleaning and rebuilding on my branch? My changes should not cause the app to crash in any way because MediaElement is not being referenced on startup in the WelcomePage. When I changed back to `Sdk assemblies only`, I got this error in VS 2022 (image below): `XAML Hot Reload is disabled because your Android Linker settings for Xamarin.CommunityToolkit.Samle.Android are unsupported. Set your Linker Behavior to "Don't Link" and rebuild your project to use Hot Reload.`.

Screenshot 2022-10-23 204219

Logcat reports the following error: `INTERNAL_ERROR: Unable to find Android.Runtime.JNIEnv.BridgeProcessing` from monodroid. A quick Google search later and the issue seems to be with [Hot Reload and linker settings](https://stackoverflow.com/a/67188183/13229958). Can you temporarily disable linker just to test my PR and we can think about permanently disabling it for sample apps?

**Comment by pictos** [comment]
@anvuks I'll ask someone on the team to test your branch as well.

**Comment by greg84** [comment]
Any update on this? I get [this issue](https://github.com/xamarin/XamarinCommunityToolkit/issues/1592) in production regularly and it looks like this PR will fix it 👍

**Comment by jfversluis** [comment]
Now that we're so close to the sunsetting of Xamarin (and therefore also Xamarin Community Toolkit) unfortunately we won't be able to take this in anymore, we're really sorry about that. Nevertheless, thank you so much for your time and effort that you have put into this PR, we really appreciate it.

Please have a look at the evolution of the Xamarin Community Toolkit, [The .NET MAUI Community Toolkit](https://github.com/CommunityToolkit/Maui). A lot of development has been going on there. Hopefully this issue was already fixed in that codebase. If not, feel free to port this over to there.

Again, thank you so much for being a contributor and Xamarin user!

**Pull request closed without merging**
