### PR TITLE
[iOS] TouchEffect: Implemented hover handling

### LINKED ISSUE #733: hover touch effect not working in Xamarin ios sample
Hi Hover example works on uwp but not ios

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###
Implemented Hover API for iOS via UIHoverGestureRecognizer.
For testing, please run the test sample on the iPad simulator and enable pointers 
image

### Bugs Fixed ###
- Fixes #733 

### API Changes ###
None

### Behavioral Changes ###
Hover API work on IOS

### PR Checklist ###
- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of develop at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Review by pictos — DISMISSED** [review]
I could test very well because I just have a simulator, but the sample runs and good looks great.

Thanks

**Comment by pictos** [comment]
BTW, this is a bug fix, no? If yes should target the main branch

**Comment by AndreiMisiukevich** [comment]
> BTW, this is a bug fix, no? If yes should target the main branch

Good question.
I am not sure if we should consider it as bugfix or enhancement

CC @jfversluis

**Comment by pictos** [comment]
My 10cents, if this works on other platforms and should work on iOS since v1, so it's a bug fix... If iOS didn't have support for this and this PR adds the support, so it's a enhancement

**Comment by AndreiMisiukevich** [comment]
I didn't know that it's possible for iOS before yesterday) So, is it an enhancement or a bug?)

**Comment by pictos** [comment]
"To be or not to be this is the question" xP

**Comment by jfversluis** [comment]
Yeah big fix or not, I think this is small enough to go into main :)

**Review by jsuarezruiz — APPROVED** [review]

**Review by pictos — APPROVED** [review]

**Pull request merged**
