### PR TITLE
Fix oldPosition newPostion args issue

### LINKED ISSUE #1208: [Bug] TabView OnSelectionChanged TabSelectionChangedEventArgs OldPosition is incorrect
### Description

The Property `OldPosition` in the `TabSelectionChangedEventArgs` is always incorrect as it is always the same value as `NewPosition`.

### Steps to Reproduce

1.  Create TabView with at least 2 items
2.  Subscribe to OnSelectionChanged 
3.  Switch Tab

### Expected Behavior

`OldPosition` is reported correctly

### Actual Behavior

`OldPosition` is reported incorrectly. Has always same value as `NewPosition`

### Basic Information

- Version with issue: 1.1.0
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: 11

### Reproduction imagery

grafik

I had a look in the source code and it seems that in TabView.shared.cs Line 823 `OldPosition = SelectedIndex` must be changed to `OldPosition = oldposition`. But then the issue is with the first switching of tabs `OldPosition` is -1 when it actually is the first tab.

### PR DESCRIPTION
**Pull request by jamers99**
The old position and new position in the SelectionChanged event was always the same

### Bugs Fixed ###

- Fixes #1208

### API Changes ###

<!-- List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`

Changed:

 - `object Cell.OldPropertyName` => `object Cell.NewPropertyName`
 
If there is an entirely new API, then you can use a more verbose style:

```csharp
public static class NewClass {
    public static int SomeProperty { get; set; }
    public static void SomeMethod(string value);
}
``` -->

### Behavioral Changes ###

<!-- Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase. -->

### PR Checklist ###
<!-- Please check all the things you did here and double-check that you got it all, or state why you didn't do something -->
- [x] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard
<!-- If at all possible, please update/add the documentation on the repo below. We would very much appreciate that. If you are unable to, please consider at least opening an issue on the repo below so we know that Docs still need to be adjusted/created. Thanks! <3 -->
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by jamers99** [comment]
Found this issue, not sure if this fixes it, but figured i'd put it out there.

**Comment by jamers99** [comment]
This needs tests and such that I am unsure of how to write. Anyone able to do that?

**Comment by pictos** [comment]
@jamers99 can you add an unit test for it?

**Comment by jamers99** [comment]
Sorry, I haven't done anything with this repository and don't have time nor the knowhow to write a test. I thought pushing the change might speed up the process of getting it in and was hoping someone else would be able to write the test 😬

**Comment by pictos** [comment]
@jamers99 no issues, thanks for the contribution

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
