### PR TITLE
Remove Int and Double Converters

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

In hindsight I was wondering... These things are supported out of the box right? So we don't need these? Or am I horribly mistaken here?

Reverts #447 

### Bugs Fixed ###
NA

### API Changes ###

Removed:

- StringToDoubleConverter
- StringToIntConverter

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
Hm, just tested on Entry + Slider.
Seems yes, it works without any converter

**Comment by AndreiMisiukevich** [comment]
@Hackavist is there any specific case where these converters are needed?

**Review by AndreiMisiukevich — APPROVED** [review]

**Comment by Hackavist** [comment]
> @Hackavist is there any specific case where these converters are needed?

Yes when i tried to run the code mentioned in the sample in the issue it failed to run without this converter ( string to double) there was not a specific use-case for the int converter

**Review by pictos — APPROVED** [review]
LGTM

**Comment by AndreiMisiukevich** [comment]
@jfversluis 

Here is the sample requiring such a converter (by @Hackavist)
```xaml
 <StackLayout

            Padding="10,10"

            HorizontalOptions="Fill"

            Spacing="10"

            VerticalOptions="Fill">

            <Label Text="{rsx:Translate DoubleToIntConverterLongDescription}" TextColor="{StaticResource NormalLabelTextColor}" />

            <Label Text="{rsx:Translate TextEntryPromt}" TextColor="{StaticResource NormalLabelTextColor}" />



            <Entry

                x:Name="ExampleText"

                Placeholder="Example 2.3"

                Text="16.67"

                TextColor="{StaticResource NormalLabelTextColor}" />

            <Label

                BindingContext="{x:Reference Name=ExampleText}"

                Text="{Binding Path=Text, Converter={StaticResource DoubleToIntConverter}, ConverterParameter=2}"

                TextColor="{StaticResource NormalLabelTextColor}" />

        </StackLayout>
```

**Comment by AndreiMisiukevich** [comment]
> @jfversluis
> 
> Here is the sample requiring this converter (by @Hackavist)
> 
> ```
>  <StackLayout
> 
>             Padding="10,10"
> 
>             HorizontalOptions="Fill"
> 
>             Spacing="10"
> 
>             VerticalOptions="Fill">
> 
>             <Label Text="{rsx:Translate DoubleToIntConverterLongDescription}" TextColor="{StaticResource NormalLabelTextColor}" />
> 
>             <Label Text="{rsx:Translate TextEntryPromt}" TextColor="{StaticResource NormalLabelTextColor}" />
> 
> 
> 
>             <Entry
> 
>                 x:Name="ExampleText"
> 
>                 Placeholder="Example 2.3"
> 
>                 Text="16.67"
> 
>                 TextColor="{StaticResource NormalLabelTextColor}" />
> 
>             <Label
> 
>                 BindingContext="{x:Reference Name=ExampleText}"
> 
>                 Text="{Binding Path=Text, Converter={StaticResource DoubleToIntConverter}, ConverterParameter=2}"
> 
>                 TextColor="{StaticResource NormalLabelTextColor}" />
> 
>         </StackLayout>
> ```

But can we work around this case by "StringFormat"?

**Comment by jfversluis** [comment]
The only converter I see in this sample is a double to int? Which is not part of this PR and indeed can be fixed with a StringFormat

**Comment by Hackavist** [comment]
This converter needs a double and the default output of the entry is a string so if u tried this code it will fail

**Comment by jfversluis** [comment]
But why use this converter in this case at all? You can simply bind to the text and apply a StringFormat which will make it an int

My worry is that people will start using these converters for showing integers and doubles while that is not necessary at all

**Comment by Hackavist** [comment]
Okay then remove them, but can you please type a sample of this code using string format ?

**Review by AndreiMisiukevich — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Comment by jfversluis** [comment]
@Hackavist [here you can see](https://www.youtube.com/watch?v=5Se94j5KMhc&list=PLfbOp004UaYUgjhTHjtSixo-iMdz6PhIv&index=1) how to use it :) let me know if you have any more questions

**Pull request merged**
