### PR TITLE
fix bug,  Binding error on views inside a TabViewItem if the TabView …

### LINKED ISSUE #1290: [Bug] Binding error on views inside a TabViewItem if the TabView page itself has a Binding defined
### Description
Binding error on views inside a TabViewItem if the TabView page itself has a Binding defined

### Steps to Reproduce

1. Binding with ViewModels in TabViewItem works if there is no ViewModel on the view or there is the TabView
2. If you add a ViewModel on the page where there is the TabView, the binding of the TabViewItem views models no longer works.
3. But on the other hand they are well called, but no more binding works, I assume that the bindings are sent to the ViewModel defined in the main page. What is not normal

### Sample

an example of a project to reproduce the bug  https://github.com/auriou/TabViewSampleError

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="TabViewSample.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views1="clr-namespace:TabViewSample.Views;assembly=TabViewSample"
    xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
    BindingContext="{Binding MainViewModel, Source={StaticResource Locator}}">
    <!--  if delete BindingContext into this MainPage, the binding work into LazyView otherwise don't work  -->
    <Grid>
        <xct:TabView
            TabStripBackgroundColor="Blue"
            TabStripHeight="50"
            TabStripPlacement="Bottom">
            <xct:TabViewItem Text="One" TextColor="White">
                <xct:LazyView x:TypeArguments="views1:OneView" BindingContext="{Binding OneView, Source={StaticResource Locator}}" />
            </xct:TabViewItem>
            <xct:TabViewItem Text="Two" TextColor="White">
                <xct:LazyView x:TypeArguments="views1:TwoView" BindingContext="{Binding TwoView, Source={StaticResource Locator}}" />
            </xct:TabViewItem>
        </xct:TabView>
    </Grid>
</ContentPage>

```

### Basic Information

- Version with issue: 1.1.0

- IDE: Visual Studio 2019
- Android 
- Nuget Packages: 1.1.0
- Affected Devices: All ?

### Reproduction Link

https://github.com/auriou/TabViewSampleError

### PR DESCRIPTION
**Pull request by auriou**
…page itself has a Binding defined

https://github.com/xamarin/XamarinCommunityToolkit/issues/1290

Fixes #1290

### CODE REVIEW

**Comment by pictos** [comment]
@auriou do you think that you can add a sample [at here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/samples/XCT.Sample/Pages/TestCases)? Just to confirm that your PR fixes the issue and we have a way to test against regressions

**Comment by auriou** [comment]
@pictos ok i do that, as soon as i have a little time

**Comment by auriou** [comment]
@pictos  here I added a test case

**Comment by jfversluis** [comment]
@auriou it seems you didn't sign the CLA yet, could you do that please? :)

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
