### PR TITLE
Added macOS sample + target

### PR DESCRIPTION
**Pull request by sthewissen**
### Description of Change ###

The sample app for macOS is added.

### Bugs Fixed ###

- Related to issue #224

### Behavioral Changes ###

A new target is added to the list of supported targets `Xamarin.Mac20`.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by sthewissen** [comment]
The app is added, but it has some quirks functionally that need to be ironed out, hence the DO-NOT-MERGE tag.

**Comment by pictos** [comment]
Can we add this after CameraView? I want to see how much work we need to get the CamareView working on Mac.

**Comment by jsuarezruiz** [comment]
@sthewissen Could you fix the conflicts?. Let me know if need help with anything :)

**Comment by sthewissen** [comment]
@jsuarezruiz Will take a peek in the morning.

**Comment by sthewissen** [comment]
Or maybe I just took a peek and fixed the conflict :)

**Comment by jfversluis** [comment]
@sthewissen what are "some quirks in its functionally that need to be ironed out"?

**Comment by AndreiMisiukevich** [comment]
@sthewissen @jfversluis 

can we proceed with this PR?

**Comment by VladislavAntonyuk** [comment]
It would be nice to merge it. Samples have all platforms except macOS

**Comment by sthewissen** [comment]
There's something odd happening with this sample and I'm not sure why yet:

https://user-images.githubusercontent.com/2419439/105333817-72146400-5bd6-11eb-951c-d3d38e192bcc.mov

**Comment by VladislavAntonyuk** [comment]
I think it is the same issue as we have with WPF and GTK.

**Comment by brminnick** [comment]
> I think it is the same issue as we have with WPF and GTK.

I confirm that I'm seeing the same behavior on WPF & UWP as well

**Comment by VladislavAntonyuk** [comment]
Even if there is an issue with navigation, I think we should merge it. For development and testing purposes we can replace the main page with specific page to check if feature works on macOS.
We have the same approach for WPF and GTK.

**Comment by jfversluis** [comment]
Yeah same thing happening here as with GTK and WPF right now which is ControlTemplates are not supported. Let's close this one for now to not add any more targets that have "issues" until we find away around it aka not use control templates.

**Pull request closed without merging**
