### PR TITLE
[Bug][Uwp] TextValidationBehavior inconsistent when not setting ValidStyle

### LINKED ISSUE #678: [Bug][Uwp] TextValidationBehavior inconsistent when not setting ValidStyle
### Description
I implemented email validation, following [this example](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Behaviors/EmailValidationBehaviorPage.xaml), 

However, on UWP it isn't really consistent, as long as a "ValidStyle" isn't added. Shoulden't the "Valid" style default to whatever style the control had without the behaviour?

### Steps to Reproduce
1. Add a validator like the linked example and run the code
2. Add "test@test" as input text
3. Unfocus (Text becomes red, correct!)
4. Change text to "test@test.se"
5. Unfocus (Text becomes black, correct!)
6. Focus back (Text becomes red, feels **incorrect**!)

### Expected Behavior
A black text when setting the focus back

### Actual Behavior
A red text

### Basic Information

- Version with issue:
1.0.0-pre5
- Last known good version:
?
- IDE:
- Platform Target Frameworks: 
  - iOS:  Seems to work
  - Android: Seems to work
  - UWP:  1903
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
If you set a "ValidStyle" with black text, it's correctly set back to black, when focusing

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###
Try to fix ValidationBehavior bug on UWP

### Bugs Fixed ###
- Fixes #678

### API Changes ###
None

### Behavioral Changes ###
None

### PR Checklist ###
- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
@Brosten please try the nuget from this PR

**Comment by Brosten** [comment]
I just tried the new nuget, but with same result. Still red on step 6 when reproducing

**Comment by Brosten** [comment]
Still not working with 2711 version

**Comment by AndreiMisiukevich** [comment]
> Still not working with 2711 version

Yeah, I know. That's why I closed my PR.
It should be Debug, but I cannot do it

**Pull request closed without merging**
