### PR TITLE
Big Rename (again...)

### PR DESCRIPTION
**Pull request by jfversluis**
I think we all know what this is about

### CODE REVIEW

**Comment by jfversluis** [comment]
There's a weird build fail with somethingsomething sourcelink. Not sure where that came from

**Comment by jfversluis** [comment]
Hm some weird automatically generated thing in the csproj. Fixed now.

**Comment by jfversluis** [comment]
Seems like unit tests are not running, so need to fix that little thing

**Comment by jfversluis** [comment]
All good now 😌

**Comment by AndreiMisiukevich** [comment]
well done)

**Comment by jfversluis** [comment]
DNM until I get a response on the fact that we can use this name and I can get that GH action to work properly

**Pull request merged**
