### PR TITLE
Fix for [iOS] Unable to chain display Popup calls or to display two popup simultaneously #1761

### LINKED ISSUE #1761: [Bug] [iOS] Unable to chain display Popup calls or to display two popup simultaneously
### Description
It is impossible to display the second popup after awaiting the result from the first one on the iOS platform. 
It's happening due to the next logic in the iOS Popup's renderer:
```
async void OnDismissed(object? sender, PopupDismissedEventArgs e)
{
	if (ViewController != null)
		await ViewController.DismissViewControllerAsync(true);
}
````

The result is returned before the controller is removed (dismissed) from the stack (iOS's ViewController). 
### Stack Trace

[Presentation] Attempt to present <Xamarin_CommunityToolkit_UI_Views_PopupRenderer: 0x7fc154247c50> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x7fc15372d130> (from <Xamarin_CommunityToolkit_Sample_iOS_Renderers_NoLineNavigationPageRenderer: 0x7fc15489d400>) which is already presenting <Xamarin_CommunityToolkit_UI_Views_PopupRenderer: 0x7fc15460ddb0>.

### Link to Reproduction Sample

Use this repo https://github.com/bondarenkod/XamarinCommunityToolkit/tree/bdf-issue-samples

### Steps to Reproduce

1. Start the XCT.Sample app 
2. Run the app using the iOS platform as the target
3. **`Test Cases`** => **`Popup, GitHub #1761`**
4. Press the `Popup A, Popup B` button.

### Expected Behavior
After pressing `Close` on the displayed popup the next popup should be opened.
### Actual Behavior
The second popup is not displayed.

### Workaround

Adding `await Task.Delay(100...500);`  between calls is the workaround solution. 
You can test this solution by pressing `Popup A, Task.Delay, Popup B` button.

### Reproduction imagery

iOS:

https://user-images.githubusercontent.com/3184414/146067418-141981f1-ffeb-4618-83a1-f7f9a03c0712.mp4

Android (working as expected by default): 

https://user-images.githubusercontent.com/3184414/146067643-5771929f-8891-4bd4-aac7-1c6170e07501.mp4

### PR DESCRIPTION
**Pull request by bondarenkod**
### Description of Bug ###
The issue is fully described #1761 

### Issues Fixed ###

- Fixes #1761 

### PR Checklist ###

- [x] Has a linked Issue, and the Issue has been `approved`
- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

The fix was tested on the iOS emu+device and Android device, working as expected.

### CODE REVIEW

**Comment by pictos** [comment]
cc: @ahoefling

**Comment by ahoefling** [comment]
I took a glance from my mobile and the code change makes sense. Since it is a change in the shared code we need to validate this doesn't break Android or UWP

Has this been verified on all platforms?

**Comment by bondarenkod** [comment]
@ahoefling  Hi! 
Here are tests for all three platforms:
iOS (have no idea what's wrong with the BG, some glitch, just moved to VS22 today):

https://user-images.githubusercontent.com/3184414/146251418-2c845a06-dd68-4f3e-9c09-bca7fede7ca2.mp4

Android:

https://user-images.githubusercontent.com/3184414/146251439-a1ca3d3e-6ce7-4317-8816-9f1d00cc946b.mp4

UWP:

https://user-images.githubusercontent.com/3184414/146251459-47c99cd0-cee4-457b-a8f6-3bcddacfc359.mp4

**Review by ahoefling — APPROVED** [review]
Thanks for providing videos of everything it made it easier to review. The code change looks good to me and since we have tests for all platforms I think we can merge this 🚀🚀🚀

**Comment by pictos** [comment]
I'll do the final review until tomorrow and everything looks good I'll merge it. Thanks, @ahoefling, and @bondarenkod you both rock❣

**Review by VladislavAntonyuk — APPROVED** [review]

**Review by pictos — APPROVED** [review]

**Pull request merged**
