### PR TITLE
[Converters] Added ListCountConverter

### PR DESCRIPTION
**Pull request by GUOLDEV**
### Description of Change ###

This PR added ListCountConverter.

### Bugs Fixed ###

- Fixes #

None

### API Changes ###

<!-- List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`
`ListCountConverter`

Changed:

 - `object Cell.OldPropertyName` => `object Cell.NewPropertyName`
 
If there is an entirely new API, then you can use a more verbose style:

```csharp
public static class NewClass {
    public static int SomeProperty { get; set; }
    public static void SomeMethod(string value);
}
``` -->

Added: 

- `ListCountConverter`

### Behavioral Changes ###

<!-- Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase. -->
None

### PR Checklist ###
<!-- Please check all the things you did here and double-check that you got it all, or state why you didn't do something -->

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard
<!-- If at all possible, please update/add the documentation on the repo below. We would very much appreciate that. If you are unable to, please consider at least opening an issue on the repo below so we know that Docs still need to be adjusted/created. Thanks! <3 -->
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by maxkoshevoi** [comment]
Cannot you just use 

```
{Binding Items.Count}
```

Instead of 

```
{Binding Items, Converter={xct:ListCountConverter}}
```

**Comment by GUOLDEV** [comment]
Hi @maxkoshevoi, thanks for the feedback.
It is not an issue, it is a converter in case checking the number of elements in a collection is necessary and you do not need to check if `Items` is null for example. 
It reduces unnecessary null checks and returns what I want, just the number of elements.

**Comment by maxkoshevoi** [comment]
Hi @GUOLDEV, every PR needs to have an issue associated with it (event one with new features).
Could you please create one, and let's move the discussion there.

When you are creating the issue there is a template for feature requests.

**Comment by GUOLDEV** [comment]
Hi @maxkoshevoi, done! I have just created an [issue](https://github.com/xamarin/XamarinCommunityToolkit/issues/1128) for this PR.

**Pull request closed without merging**
