### PR TITLE
[Core] Added some TabView unit tests

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Added _TabView_ unit tests to validate the BindingContext propagation.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Review by AndreiMisiukevich — DISMISSED** [review]

**Comment by pictos** [comment]
@jsuarezruiz can you check why the build failed?

**Comment by AndreiMisiukevich** [comment]
> @jsuarezruiz can you check why the build failed?

Seems it was stopped manually

**Review by pictos — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
The unit tests are not running for dome reason. I am going to review what is happening in this case.

**Comment by AndreiMisiukevich** [comment]
@jsuarezruiz can it be related to .NET Core version we running the unit tests on?

**Comment by AndreiMisiukevich** [comment]
Adding tab item causes test hang
```tabView.TabItems.Add(tabViewItem1);```

**Comment by jfversluis** [comment]
Did some attempts to fix the tests but I'm starting to think that something is wrong in this actual test. Because: none of the other PRs fail with these tests, so there has to be something with this one. Is something cause an infinite loop?

**Pull request closed without merging**
