### PR TITLE
Improve accessibility for TouchEffect

### LINKED ISSUE #1579: [Enhancement] Improve accessibility for TouchEffect
## Summary

Android :
Set View.Clickable or View.LongClickable to true only if we set Command or LongPressCommand respectively.
Both are currently set to true.

iOS :
Set UIAccessibilityTrait.Button when we have Command or LongPressCommand.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [X] Just putting this out there for someone to pick up

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###
Improve accessibility for TouchEffect

### Bugs Fixed ###
- Fixes #1579

### API Changes ###
None

### Behavioral Changes ###
None

### PR Checklist ###
- [X] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Review by pictos — COMMENTED** [review]
Did you try with voice-over? I want to know if a voice-over will tell something about LongPress to the user.

**Comment by AndreiMisiukevich** [comment]
> Did you try with voice-over? I want to know if a voice-over will tell something about LongPress to the user.

Not relly, unfortunately I don't have android device

**Comment by AndreiMisiukevich** [comment]
@taenito would you like to test this PR?

**Comment by taenito** [comment]
# iOS #

## Before

### Button, ImageButton (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button :heavy_check_mark: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

### StackLayout, ContentView, Label (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name :x: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name :x: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name :x: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

### Image (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Image :x: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Image :x: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name, Image :x: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:


## After

### Button, ImageButton (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button :heavy_check_mark: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

### StackLayout, ContentView, Label (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name :x: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name :x: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name :x: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

### Image (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Image :x: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Image :x: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name, Image :x: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

## Fixes

### Fix for StackLayout and ContentView
Voice-over select the children and not the Container himself. The Container have the `UIAccessibilityTrait.Button` but not the children

Use xct:SemanticEffect

``` CSharp
<StackLayout
    Padding="20"
    xct:SemanticEffect.Description="StackLayout description"
    xct:SemanticEffect.SemanticInclusion="Include"
    xct:TouchEffect.Command="{Binding Command, Source={x:Reference Page}}"
    xct:TouchEffect.LongPressCommand="{Binding LongPressCommand, Source={x:Reference Page}}"
    ...
```

### Fix for Image and Label
Change `UIView View => Container ?? Control;` by `UIView View => Control ?? Container;`

(I don't know if you are using `UIView View => Container ?? Control;` for something else)

## After fixes

### Button, ImageButton (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button :heavy_check_mark: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

### StackLayout, ContentView, Label (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button :heavy_check_mark: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name, Button :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

### Image (with and without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button, Image :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button, Image :heavy_check_mark: | Trigger nothing :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:
Command and LongPressCommand | name, Button, Image :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger LongPressCommand :heavy_check_mark:

**Comment by taenito** [comment]
# Android #

## Before

### Button, StackLayout, ContentView, Label (without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Double-tap to activate :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:

### ImageButton, Image (without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button, Double-tap to activate :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Button, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:

### Button, StackLayout, ContentView, Label (with NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Double-tap to activate, Double-tap and hold to long press :x: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:

### ImageButton, Image (with NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button, Double-tap to activate, Double-tap and hold to long press :x: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Button, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:


## After

### Button, StackLayout, ContentView, Label (without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Double-tap to activate :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:

### ImageButton, Image (without NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button, Double-tap to activate :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Button, Double-tap to activate :x: | Trigger nothing :x: | Trigger nothing :x:

### Button, StackLayout, ContentView, Label (with NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Double-tap to activate :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:

### ImageButton, Image (with NativeAnimation)

\# | Announce | Double tap | Double tap and holding
----- | ---- | ----- | ----
Command | name, Button, Double-tap to activate :heavy_check_mark: | Trigger Command :heavy_check_mark: | Trigger Command :heavy_check_mark:
LongPressCommand | name, Button, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:
Command and LongPressCommand | name, Button, Double-tap to activate, Double-tap and hold to long press :heavy_check_mark: | Trigger nothing :x: | Trigger nothing :x:


## Notes
- TouchEffect with custom animation is not fixed
- View.LongClickable will active `Double-tap to activate` and `Double-tap and hold to long press` (Android issue ?)
- We have issues with Command and LongPressCommand (TalkBack and Switch Control), I will open a new issue with more details.

**Comment by taenito** [comment]
@AndreiMisiukevich I create new issue for Android Commands : https://github.com/xamarin/XamarinCommunityToolkit/issues/1633 (Talkback, Switch access and keyboard navigation)

**Comment by taenito** [comment]
@AndreiMisiukevich Sorry, I forgot the conclusion of my analyse.

# iOS

Change `UIView View => Container ?? Control;` by `UIView View => Control ?? Container;` to fix TouchEffect on Image and Label (and maybe another controls).
(I don't know if you are using `UIView View => Container ?? Control;` for something else)

# Android

It works fine when we use it with `NativeAnimation = true` but not with custom animation.

**Pull request closed without merging**
