### PR TITLE
MediaElement bindable Position property (#330)

### LINKED ISSUE #330: [Bug] MediaElement custom position bar is inelegant (paper cut)
### Description

Creating a custom position bar is currently a bit inelegant. All because you can't bind to the `Position` property (related issue: xamarin/Xamarin.Forms#9559).

I have a `PositionSlider` control, to represent a custom position bar. It exposes `Duration`, `Position`, and `TimeToEnd` properties. I use it as follows:

```
        <controls:PositionSlider x:Name="positionSlider"
                                 BindingContext="{x:Reference mediaElement}"
                                 Duration="{Binding Duration}"
                                 ValueChanged="OnPositionSliderValueChanged">
            <controls:PositionSlider.Triggers>
                <DataTrigger TargetType="controls:PositionSlider"
                             Binding="{Binding CurrentState}"
                             Value="{x:Static MediaElementState.Buffering}">
                    <Setter Property="IsEnabled" Value="False" />
                </DataTrigger>
            </controls:PositionSlider.Triggers>
        </controls:PositionSlider>
```

`PositionSlider.Duration` is bound to `MediaElement.Duration`. But you can't bind `PositionSlider.Position` to `MediaElement.Position` because `MediaElement.Position` deliberately doesn't send property change notifications at this time.

So you end up with the following mechanism:

1. Poll `MediaElement.Position` every X milliseconds to get the correct value and update the UI with its value.
1. Have an event handler for `PositionSlider.ValueChanged` that cancels the polling, updates `MediaElement.Position` from `PositionSlider.Position`, and then starts the polling again.

It'd be so much nicer if you could just accomplish this with data binding (so eliminating the `ValueChanged` event handler).

Sample: [WorkingWithMediaElement.zip](https://github.com/xamarin/Xamarin.Forms/files/4219501/WorkingWithMediaElement.zip)

### PR DESCRIPTION
**Pull request by peterfoot**
### Description of Change ###

Replacement for closed PR #374

Position property now regularly reports change events while media is playing. Uses internal timer and supports arbitrary seeking. Also added a TimeSpanToDoubleConverter to allow controls such as Slider which use a double value to be bound to the TimeSpan properties.

### Bugs Fixed ###

- Fixes #330 

### API Changes ###

MediaElement - None

Added:
Xamarin.CommunityToolkit.Converters.TimeSpanToDoubleConverter

### Behavioral Changes ###

Position property now reports value changes on an internal timer (200ms) to allow controls to be data-bound to the live value - e.g. slider control without having to implement a Timer and additional code.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard

### CODE REVIEW

**Comment by jfversluis** [comment]
Thank you so much Peter!

Just tested this, I mentioned one weird thing. Not sure if it's due to this.

If I run the sample on iOS, start playing, do some seeking and navigate back I still hear the video going, the UI becomes not responsive and in the output I see this.


```

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1036dde05 - /Users/jfversluis/Library/Developer/CoreSimulator/Devices/05F207FF-57BF-4A1F-ACEC-3C7522C63AEB/data/Containers/Bundle/Application/8E394A67-EC79-486C-8B2F-D897A12EF1CD/Xamarin.CommunityToolkit.Sample.iOS.app/Xamarin.CommunityToolkit.Sample.iOS : mono_dump_native_crash_info
	0x1036d294e - /Users/jfversluis/Library/Developer/CoreSimulator/Devices/05F207FF-57BF-4A1F-ACEC-3C7522C63AEB/data/Containers/Bundle/Application/8E394A67-EC79-486C-8B2F-D897A12EF1CD/Xamarin.CommunityToolkit.Sample.iOS.app/Xamarin.CommunityToolkit.Sample.iOS : mono_handle_native_crash
	0x1036e46fb - /Users/jfversluis/Library/Developer/CoreSimulator/Devices/05F207FF-57BF-4A1F-ACEC-3C7522C63AEB/data/Containers/Bundle/Application/8E394A67-EC79-486C-8B2F-D897A12EF1CD/Xamarin.CommunityToolkit.Sample.iOS.app/Xamarin.CommunityToolkit.Sample.iOS : mono_sigsegv_signal_handler_debug
	0x7fff5dccf5fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x1040c6058 - Unknown
	0x7fff207d53e3 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation : NSKeyValueWillChangeWithPerThreadPendingNotifications
	0x10c4dc922 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/AVFoundation.axbundle/AVFoundation : -[AVPlayerAccessibility willChangeValueForKey:]
	0x7fff57835030 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore : -[AVPlayer setRate:withVolumeRampDuration:playImmediately:rateChangeReason:]
	0x7fff578353f7 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVFCore.framework/AVFCore : -[AVPlayer setRate:]
	0x103902ad9 - /Users/jfversluis/Library/Developer/CoreSimulator/Devices/05F207FF-57BF-4A1F-ACEC-3C7522C63AEB/data/Containers/Bundle/Application/8E394A67-EC79-486C-8B2F-D897A12EF1CD/Xamarin.CommunityToolkit.Sample.iOS.app/Xamarin.CommunityToolkit.Sample.iOS : xamarin_dyn_objc_msgSend
	0x10ae4c262 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff2017699f):0x7fff2017698f  08 5b 41 5e 41 5f 5d c3 48 85 ff 7e 09 48 8b 07  .[A^A_].H..~.H..
0x7fff2017699f  8a 40 1c 24 01 c3 31 c0 c3 48 85 ff 74 17 78 1d  .@.$..1..H..t.x.
0x7fff201769af  48 8b 07 48 85 c0 74 0d 48 89 c7 be 01 00 00 00  H..H..t.H.......
0x7fff201769bf  e9 78 e6 00 00 48 8d 05 6c 6e 02 00 c3 48 89 f8  .x...H..ln...H..

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend <0x000e1>
	  at AVFoundation.AVPlayer:Pause <0x00122>
	  at Xamarin.CommunityToolkit.UI.Views.MediaElementRenderer:Dispose <0x00327>
	  at Foundation.NSObject:Dispose <0x00074>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Dispose <0x002c5>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Dispose <0x00071>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Dispose <0x0024a>
	  at Foundation.NSObject:Dispose <0x00074>
	  at Xamarin.Forms.Platform.iOS.DisposeHelpers:DisposeModalAndChildRenderers <0x0030f>
	  at Xamarin.Forms.Platform.iOS.Platform:HandleChildRemoved <0x000d2>
	  at Xamarin.Forms.Element:OnDescendantRemoved <0x00120>
	  at Xamarin.Forms.Element:OnChildRemoved <0x00182>
	  at Xamarin.Forms.VisualElement:OnChildRemoved <0x00092>
	  at Xamarin.Forms.Page:OnInternalRemoved <0x00140>
	  at Xamarin.Forms.Page:InternalChildrenOnCollectionChanged <0x002c2>
	  at System.Collections.ObjectModel.ObservableCollection`1:OnCollectionChanged <0x000fa>
	  at System.Collections.ObjectModel.ObservableCollection`1:OnCollectionChanged <0x00103>
	  at System.Collections.ObjectModel.ObservableCollection`1:RemoveItem <0x0018a>
	  at System.Collections.ObjectModel.Collection`1:Remove <0x001e5>
	  at <Xamarin-Forms-INavigationPageController-RemoveAsyncInner>d__79:MoveNext <0x006d2>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00222>
	  at Xamarin.Forms.NavigationPage:Xamarin.Forms.INavigationPageController.RemoveAsyncInner <0x001b2>
	  at <UpdateFormsInnerNavigation>d__78:MoveNext <0x0035f>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x001fa>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:UpdateFormsInnerNavigation <0x0016a>
	  at <DidMoveToParentViewController>d__45:MoveNext <0x001c2>
	  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start <0x0020a>
	  at ParentingViewController:DidMoveToParentViewController <0x00182>
	  at <Module>:runtime_invoke_void__this___object <0x001ab>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00254>
	  at UIKit.UIApplication:Main <0x000b2>
	  at UIKit.UIApplication:Main <0x00132>
	  at Xamarin.CommunityToolkit.Sample.iOS.Application:Main <0x00092>
	  at <Module>:runtime_invoke_void_object <0x00198>
=================================================================
```

**Comment by peterfoot** [comment]
@jfversluis it doesn't look like this is related to seeking though as it appears to be the Dispose issue. I'll have a look at it again.

**Comment by jfversluis** [comment]
Does it have to do with the other PR I pinged you in?

**Comment by peterfoot** [comment]
I looked at the stack traces of a couple of permutations and the base.Dispose is triggering OnElementChanged - this means there are two sets of competing cleanup code happening. Removing the Dispose method entirely and ensuring all the cleanup code is in OnElementChanged seems to have resolved the issue. Can navigation forward and back many times, perform different interations on the player (including Seek) and it behaves as expected.

**Review by jfversluis — CHANGES_REQUESTED** [review]
OK this fixes it for iOS, but on Android using the Slider does not seem to have any effect

**Comment by jfversluis** [comment]
Perfect, thanks!

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
