### PR TITLE
Fix null check in the iOS FormsCameraView

### PR DESCRIPTION
**Pull request by michaldivis**
### Description of Change ###

Fixed the null check in the iOS FormsCameraView class. The `TakePhoto` method was checking whether the `videoOutput` was null. From what I understand, it should be checking the `photoOutput` since that's what it's using, so I fixed it.

No tests added/modified since this is a very minor change.

No samples added/modified since this is a very minor change.

### Bugs Fixed ###

None

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=923) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=923) before we can accept your contribution.<br/><br/>:x: michaldivis [sign now](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=923)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/XamarinCommunityToolkit?pullRequest=923) it.</sub>

**Comment by jfversluis** [comment]
Definitely looks weird :D Thank you for you contribution!

**Review by jfversluis — APPROVED** [review]

**Comment by arscoloramanfredi** [comment]
Are you sure about that? Looking at the code, at row number 197 it checks photoOutput, it's already null checked before at row 191 and returns. Version 1.0.3 doesn't work in iOS, version 1.0.2 does.

`// iOS >= 10
			if (photoOutput != null)`

**Comment by michaldivis** [comment]
@arscoloramanfredi it definitely is a little weird. I've made the change because when debugging on my iOS device the `videoOutput` (that the null check was checking before my PR) was always null when having `CameraMode` set to `Photo`.

Version 1.0.2 didn't work on my device, so I went to try to fix it. But you're saying it was working for you so now I'm not sure what to do. 

The person who wrote this class in the first place might able to help here.

**Comment by johnnypi6** [comment]
@michaldivis Your fixing is not right. The camera view does not take a photo. I replaced `// iOS >= 10 if (photoOutput != null)` into `// iOS >= 10 if (videoOutput != null)`. Now the camera view works.

**Pull request merged**
