### PR TITLE
[Housekeeping] Warnings elimination

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###
Only project cleanup (Mostly changed files encoding to UTF-8 with BOM)

### API Changes ###
None

### Behavioral Changes ###
None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [X] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
These warnings should go once XF updated to v5 https://github.com/xamarin/Xamarin.Forms/issues/9186

image

**Comment by pictos** [comment]
can we do this after we merge XF5.0 PR?

**Comment by AndreiMisiukevich** [comment]
> can we do this after we merge XF5.0 PR?

Yes!

**Comment by AndreiMisiukevich** [comment]
@pictos ;)

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
