### PR TITLE
[Bug] null-ing MediaElement.Source has no effect

### LINKED ISSUE #407: [Bug] null-ing MediaElement.Source has no effect
### Description

If you set `MediaElement.Source` to a remote video, and let it load, then set `MediaElement.Source` to `null` I'd expect the existing video to be closed.

However, this isn't the case. The existing video is still displayed, and you can call the `Play` method on the `MediaElement` to play the video.

This occurs on both iOS and Android (no idea about UWP).

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###
We should stop and reset MediaElement if **null** source set.

### Bugs Fixed ###
- Fixes #407 

### API Changes ###
None

### Behavioral Changes ###
None (only bug fix)

### PR Checklist ###
- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [X] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
@pictos could you please test it on UWP as well (I tested iOS and Android)

**Comment by pictos** [comment]
> @pictos could you please test it on UWP as well (I tested iOS and Android)

I'll test it by tomorrow.

**Comment by pictos** [comment]
On UWP this isn't working very well. There's a huge delay between the time that I press the button to reset the source and the time that action is triggered. Also, there's no animation on the button, looks like that the MediaElement is blocking the UI thread. Even the player slider is lagging. But I'm not sure if this has something related to your modification. I'll run the main branch and update this comment

**Review by pictos — APPROVED** [review]
This PR solves the bug. Tested on UWP

**Pull request merged**
