### PR TITLE
Uwp retarget to 17763 / 1809

### PR DESCRIPTION
**Pull request by inforithmics**
### Bugs Fixed ###

- Fixes https://github.com/xamarin/XamarinCommunityToolkit/issues/889

### API Changes ###

Changed Target Windows version back to 17763 / 1809
from 19031 / 2004

### Behavioral Changes ###

works now again on Windows 17763 / 1809

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of develop at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by jfversluis** [comment]
Hm I would think we've set it to that target for a reason :D

**Comment by pictos** [comment]
@jfversluis if I'm not wrong was for popup control. Need to test this change to see if this doesn't break anything else

**Comment by jfversluis** [comment]
@ahoefling might know?

Let's not merge this until we know/properly test this

**Comment by inforithmics** [comment]
Here the link around the discussion about this.

https://github.com/xamarin/XamarinCommunityToolkit/pull/653#discussion_r536516886

**Comment by ahoefling** [comment]
The UWP Flyout control added the ability to specify a transparent background in 19041. @inforithmics the discussion you linked explains this in my first comment https://github.com/xamarin/XamarinCommunityToolkit/pull/653#discussion_r537581216. This change appears to be a workaround to our packaging problem.

The change provided here downgrades the lowest version supported and then applies the check for the feature a different way. I still believe the issue with UWP is packaging and not a code change like suggested here.

We should focus our efforts on getting this to work with windows build 19041.

**Comment by ahoefling** [comment]
I just added a comment on the original issue. This is not a packaging bug and can be solved by updating the min target version.

I think we can close both PR and issue as not a bug

https://github.com/xamarin/XamarinCommunityToolkit/issues/889#issuecomment-784553594

**Comment by inforithmics** [comment]
I agree that increasing the Min Version would solve the problem. But when you want to use the Xamarin Community Toolkit Popup on the oldest supported Windows Version you can't at moment.

https://en.wikipedia.org/wiki/Windows_10_version_history

Here you see all Windows 10 Supported Versions 1803 / 1809 are still supported until May 11 2021 (Enterprise Version)
And 1809 is still supported until January 9 2029 as a LTSC Version.

So that's why I retargeted it to Version 1809 as it was before.

With WinUI 3 this won't matter anymore, but unfortunatly the earlist that WinUI 3 on UWP will be supported is autumn of this year (not commited yet by WinUI 3).

I although created a new Xamarin.Forms UWP project and the default Minimum UWP Version was 16299 /1709 (The Minimum Version of Xamarin.Forms).

I like the Xamarin Community Toolkit Popup and would like to use it, but I can't at the moment because I'm only able to set the Minimum Supported Version to 17763/1809.

**Comment by inforithmics** [comment]
They changed now the WinUI 3 roadmap WinUI 3 on UWP is now included as a Preview Feature in March 2021 

https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md

But I don't know what happens when Xamarin Forms stays on UWP and Xamarin Community Toolkit uses WinUI 3 Toolkit

**Comment by YZahringer** [comment]
I agree with @inforithmics, the UWP min version should be `1809`, it is an `LTSC` version and we always support it in all our projects.

**Comment by bmacombe** [comment]
@jfversluis @pictos  I remember last summer talking about possibly needing to split the toolkit into more packages.  While I'd like to avoid that, it might be something to consider if the min version can't be moved back past 2004.   I think the Popup addition is great, but it's blocking me on XCT now because of the Win 10 min version in my user base.   And I'm lucky that I only have users back to 1909.  I know I could fork and roll my own, but that seems to defeat the purpose of the toolkit.

image

I'm not an expert at packaging and version detection, but what harm would this change do?  If it would cause the popup to not work correctly and seem buggy or something on Win 10 < 2004 without the transparency setting, maybe it could just throw a not-supported exception or something similar.

**Comment by inforithmics** [comment]
If someone wants to test the changes the nuget package can be downloaded from this link:
https://dev.azure.com/xamarin/public/_build/results?buildId=38666&view=artifacts&pathAsName=false&type=publishedArtifacts

is for the https://github.com/xamarin/XamarinCommunityToolkit/pull/942/commits/667855ba0e1ac3564ca8a240e316e845cb252679 checkin.

**Pull request closed without merging**
