### PR TITLE
Fixed naming convention of CaptureModeProperty

### PR DESCRIPTION
**Pull request by redeaglekiller**
### Description of Change ###

Changed PropertyName to fix naming convention.

-Can't test the MACOS compile, but it should work.
-Tests are ok on Windows and working on an Android device
-No samples necessary in my opinion.
-Documentation Update not necessary

### Bugs Fixed ###
- Fixes [#774 ](https://github.com/xamarin/XamarinCommunityToolkit/issues/774)

### API Changes ###
None

### Behavioral Changes ###

-Intellisense should work now
-MVVM supported with naming convention on CameraView

### PR Checklist ###

- [ x] Has tests (MACOS / IOS not tested)
- [ ] Has samples
- [x ] Rebased on top of main at time of PR
- [x ] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=775) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=775) before we can accept your contribution.<br/><br/>:x: redeaglekiller [sign now](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=775)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/XamarinCommunityToolkit?pullRequest=775) it.</sub>

**Comment by redeaglekiller** [comment]
@jsuarezruiz Hi should I do something or is it ok? Sorry....first time ;-)

**Comment by jfversluis** [comment]
@redeaglekiller this is fine! And a good catch. So sorry this bug was in there :( Thank you for finding and fixing it!

**Review by jfversluis — APPROVED** [review]

**Comment by redeaglekiller** [comment]
@jfversluis Thank you guys for this awesome Toolkit. I will report other things as I find them.

**Pull request merged**
