### PR TITLE
[CameraView][iOS] Remove unused code

### LINKED ISSUE #1587: [Enhancement] [CameraView] Remove unused code
## Summary

I would like to remove unused code to make it easier to maintain, starting from `FormsCameraView`.

## API Changes

Removed:

- `UIImage RotateImage(UIImage image)`

## Intended Use Case

NA

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

### PR DESCRIPTION
**Pull request by GUOLDEV**
### Description of Change ###

I would like to remove unused code to make it easier to maintain, starting from `FormsCameraView`.

### Bugs Fixed ###

- Fixes #1587 

### API Changes ###

Removed:

- `UIImage RotateImage(UIImage image)`

<!-- List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`

Changed:

 - `object Cell.OldPropertyName` => `object Cell.NewPropertyName`
 
If there is an entirely new API, then you can use a more verbose style:

```csharp
public static class NewClass {
    public static int SomeProperty { get; set; }
    public static void SomeMethod(string value);
}
``` -->

### Behavioral Changes ###

NA
<!-- Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase. -->

### PR Checklist ###
<!-- Please check all the things you did here and double-check that you got it all, or state why you didn't do something -->
- [ ] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard
<!-- If at all possible, please update/add the documentation on the repo below. We would very much appreciate that. If you are unable to, please consider at least opening an issue on the repo below so we know that Docs still need to be adjusted/created. Thanks! <3 -->
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by GUOLDEV** [comment]
@jfversluis @pictos Is code cleanup ok? I have created this draft PR for code cleanup, starting from FormsCameraView. Could you please let me know if I have to create an issue ticket first? Thanks 🙏

**Comment by pictos** [comment]
Hey @GUOLDEV , for sure will be great if you can create a ticket for this

**Comment by GUOLDEV** [comment]
> Hey @GUOLDEV , for sure will be great if you can create a ticket for this
Done!

**Comment by GUOLDEV** [comment]
Hey @pictos, is there anything else that I can do to get this PR in?

**Review by pictos — APPROVED** [review]
Thanks, @GUOLDEV, this will be merged if the build succeed.

**Pull request merged**
