### PR TITLE
Make WeakSubscribe<T>(this INotifyPropertyChanged target..) EventArgs parameter type more specific

### LINKED ISSUE #917: [Bug] WeakSubscribe<T>(this INotifyPropertyChanged target..) has incorrect EventArgs parameter type
### Description

`WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, EventArgs> action)`
should be 
`WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, PropertyChangedEventArgs> action)`

since it explicitly extends `INotifyPropertyChanged` and `PropertyChangedEventHandler` provides subscribers with `PropertyChangedEventArgs`.

### Steps to Reproduce

This will get a complile-time error since currently `e` is `EventArgs` instead of `PropertyChangedEventArgs`:
```
someObservableObject.WeakSubscribe(this,(t, _, e) =>
{
    if (e.PropertyName == nameof(someObservableObject.SomeProperty))
    {
        DoWork();
    }
});
```

### Expected Behavior
I should be able to refer to `PropertyName` of event arguments.

### Actual Behavior
I cannot directly do that

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Cast `e` to `PropertyChangedEventArgs` inside event handler

### PR DESCRIPTION
**Pull request by maxkoshevoi**
### Description of Change ###

Made WeakSubscribe<T>(this INotifyPropertyChanged target..) EventArgs parameter type more specific (`EventArgs` -> `PropertyChangedEventArgs`).
It was `PropertyChangedEventArgs` from the beginning, but got upcasted by mistake. 

### Bugs Fixed ###

- Fixes #917

### API Changes ###

Was `WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, EventArgs> action)`
Now `WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, PropertyChangedEventArgs> action)`

### Behavioral Changes ###

Users can now reference `PropertyName` when using `WeakSubscribe`

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Review by pictos — APPROVED** [review]

**Comment by AndreiMisiukevich** [comment]
@maxkoshevoi could you please fix the merge conflicts? thanks

@pictos won't it be a breaking change?

**Comment by maxkoshevoi** [comment]
@AndreiMisiukevich I know question is not to me, but still:
- This feature is not release yet
- `EventArgs` are consumed by user, so this change will give user more specific type to work with
- That parameter is always `PropertyChangedEventArgs`. Right not it's just upcasted to `EventArgs` by mistake (my mistake)

Here's some context. Right now this will get a complile-time error (`e` doesn't contain `PropertyName `) since currently `e` is `EventArgs` instead of `PropertyChangedEventArgs`:
```cs
someObservableObject.WeakSubscribe(this,(t, _, e) =>
{
    if (e.PropertyName == nameof(someObservableObject.SomeProperty))
    {
        DoWork();
    }
});
```

**Comment by pictos** [comment]
@AndreiMisiukevich 

> @pictos won't it be a breaking change?

I believe that will be, but since this isn't on `main` we can still break things. Anyway just asking for @jfversluis confirmation 😅

**Comment by maxkoshevoi** [comment]
> @AndreiMisiukevich
> 
> > @pictos won't it be a breaking change?
> 
> I believe that will be, but since this isn't on `main` we can still break things. Anyway just asking for @jfversluis confirmation 😅

Could you please provide some sample code that would be broken in any way by this? 
I just cannot understand how is this a breaking change..  (not that is matters since, as you said, this it's on `main` yet, but still)

**Comment by pictos** [comment]
@maxkoshevoi 

> Could you please provide some sample code that would be broken in any way by this?

This can be a binary break change, as you can find more info [here](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes#binary-breaking-change)

**Comment by maxkoshevoi** [comment]
> @maxkoshevoi
> 
> > Could you please provide some sample code that would be broken in any way by this?
> 
> This can be a binary break change, as you can find more info [here](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes#binary-breaking-change)

You are correct. It's a binary breaking change. It throws:
```
Unhandled exception. System.MissingMethodException: Method not found: 'Void ClassLibrary1.INotifyPropertyChangedExtension.WeakSubscribe(System.ComponentModel.INotifyPropertyChanged, !!0, System.Action`3<!!0,System.Object,System.EventArgs>)'.
``` 
if app is not recompiled after dll is updated.

**Comment by pictos** [comment]
@maxkoshevoi can you describe step by step how did you do the test? I have no idea how to test it

**Comment by maxkoshevoi** [comment]
@pictos Sure =)

1) Create a solution with two projects. One a class library and second is some executable (for example, console application)
2) Add some code to library project and use it in executable one
3) Compile everything (and run execute to make sure everything works)
4) Update code in library project and Compile just that project
5) Take `dll` that you just created and copy it to artifacts of executable project (replace old one with it)
6) Run executable project directly from artifacts

**Comment by jfversluis** [comment]
Indeed not released yet and we should worry (too much) about ABI breaks so all good!

**Comment by jfversluis** [comment]
I think you already had a task to update/write the documentation @maxkoshevoi ?

**Comment by maxkoshevoi** [comment]
@jfversluis I have documentation tasks for `CommandFactory` and `LocalizationManager`, but now for `LocalizedString` or `WeakSubscribe` extension method. I'll create those tasks.

**Pull request merged**
