### PR TITLE
Animation Triggers

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Added triggers to manage animations:
- AnimateColor
- AnimateInt
- AnimateCornerRadius
- AnimateDouble
- AnimateThickness

animation-triggers

```
<Entry 
    FontSize="16" 
    BackgroundColor="LightGray">
    <Entry.Triggers>
        <Trigger TargetType="Entry" Property="IsFocused" Value="True">
            <Trigger.EnterActions>
                <triggers:AnimateDouble TargetProperty="Entry.FontSize" To="24"/>
                <triggers:AnimateColor TargetProperty="Entry.TextColor" To="Red"/>
                <triggers:AnimateColor TargetProperty="VisualElement.BackgroundColor" To="Yellow" Delay="1000"/>
                <triggers:AnimateDouble TargetProperty="VisualElement.Rotation" To="12" Duration="100"/>
            </Trigger.EnterActions>
            <Trigger.ExitActions>
                <triggers:AnimateDouble TargetProperty="{x:Static Entry.FontSizeProperty}" To="16"/>
                <triggers:AnimateColor TargetProperty="{x:Static Entry.TextColorProperty}" To="Black"/>
                <triggers:AnimateColor TargetProperty="{x:Static VisualElement.BackgroundColorProperty}" To="LightGray"/>
                <triggers:AnimateDouble TargetProperty="{x:Static VisualElement.RotationProperty}" To="0"/>
            </Trigger.ExitActions>
        </Trigger>
    </Entry.Triggers>
</Entry>
```

### API Changes ###

Added triggers section in the Toolkit and Sample.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by AmrAlSayed0** [comment]
Hmm 🤔, reminds me of this [xamarin/Xamarin.Forms#4233](https://github.com/xamarin/Xamarin.Forms/issues/4233). Would that be a good addition to XCT?

**Comment by SagarPanwala** [comment]
Just trying to contribute little from my side.
Can we rename AnimateCornerRadius instead of AnimateCornerRadios?

**Comment by pictos** [comment]
@jsuarezruiz shouldn't this be targeting the develop branch?

**Comment by jsuarezruiz** [comment]
Yes, changed the target!

**Review by brminnick — DISMISSED** [review]

**Comment by brminnick** [comment]
Love it! This is ready to merge once you've added the [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit), @jsuarezruiz! 🚀

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin

**Pull request closed without merging**
