### PR TITLE
Part of Project clean-up #529 

### PR DESCRIPTION
**Pull request by pictos**
### Description of Change ###

part of #529

This is just a proposal of how we can organize our project since now we have the Markup Extension project and this can take a while since we merge the samples.

### CODE REVIEW

**Comment by pictos** [comment]
Do I need to change something on yml?

**Comment by AndreiMisiukevich** [comment]
Strange, but build failed

**Comment by pictos** [comment]
@AndreiMisiukevich, the error is that the build couldn't found the `csproj` to build. So I'm guessing if I need to change something on yml file, but I'll wait for the @jfversluis input.

**Comment by jfversluis** [comment]
Yeah in this case it wasn't so hard, have a look at the yaml file :) 

Did some more renaming and stuff! This is going to be very disruptive for all the PRs that are there though... :(

**Comment by jfversluis** [comment]
@pictos I rebased this one, so before you do anything more on this you might want to reset your branch to be even with this one

**Comment by pictos** [comment]
@jfversluis thank you for taking care of it! I don't want to change anything else. Now it's ready for review.
@AndreiMisiukevich @sthewissen @jsuarezruiz thoughts?

**Review by jfversluis — APPROVED** [review]
OK here we go, this will hurt...

**Pull request merged**
