### PR TITLE
Tizen sample added

### PR DESCRIPTION
**Pull request by rookiejava**
### Description of Change ###

This PR adds the XamarinCommunityToolkitSample Tizen project. 

#### Known Issues ####
Currently, `CameraView` and `MediaElement` are not supported. These will be covered by a new PR later. (after referencing the  Xamarin.Forms package including this PR (https://github.com/xamarin/Xamarin.Forms/pull/12007).

### Bugs Fixed ###
None

### API Changes ###
None

### Behavioral Changes ###
None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Review by AndreiMisiukevich — COMMENTED** [review]
Brilliant

**Review by AndreiMisiukevich — APPROVED** [review]

**Comment by AndreiMisiukevich** [comment]
RangeSlider looks bad of course :( Something wrong with the corner radius of Frame on Tizen

**Comment by rookiejava** [comment]
> RangeSlider looks bad of course :( Something wrong with the corner radius of Frame on Tizen

True. Existing Frame renderer is not support the corner radius and will be fixed in the new version (XF 5.0) as you can see https://github.com/xamarin/Xamarin.Forms/pull/12501.  😉

**Comment by AndreiMisiukevich** [comment]
> > RangeSlider looks bad of course :( Something wrong with the corner radius of Frame on Tizen
> 
> True. Existing Frame renderer is not support the corner radius and will be fixed in the new version (XF 5.0) as you can see [xamarin/Xamarin.Forms#12501](https://github.com/xamarin/Xamarin.Forms/pull/12501). 😉

Brilliant!)

**Pull request merged**
