### PR TITLE
Fix the wrong assignation of margins when the text is assigned

### LINKED ISSUE #535: [Bug] BadgeView Margins and Layout strange behaviour
### Description
I have some issues adding the new BadgeView into my application that breaks my current layouts.
Hereby I've found some issues with a blank app:

1. With the following code I see that there are some wrong margins:
`<StackLayout
        HorizontalOptions="Center"
        Spacing="10"
        VerticalOptions="Center">
        <StackLayout Orientation="Horizontal">
            <controls:BadgeView
                BackgroundColor="Red"
                BadgePosition="TopLeft"
                BorderColor="Orange"
                IsClippedToBounds="True"
                Text="1"
                TextColor="White">
                <Image IsOpaque="True" Source="Alerts.png" />
            </controls:BadgeView>
            <controls:BadgeView
                BackgroundColor="Red"
                BadgePosition="TopRight"
                BorderColor="Orange"
                IsClippedToBounds="True"
                Text="1"
                TextColor="White">
                <Image IsOpaque="True" Source="Alerts.png" />
            </controls:BadgeView>
        </StackLayout>
        <StackLayout Orientation="Horizontal">
            <controls:BadgeView
                BackgroundColor="Red"
                BadgePosition="BottomLeft"
                BorderColor="Orange"
                IsClippedToBounds="True"
                Text="1"
                TextColor="White">
                <Image IsOpaque="True" Source="Alerts.png" />
            </controls:BadgeView>
            <controls:BadgeView
                BackgroundColor="Red"
                BadgePosition="BottomRight"
                BorderColor="Orange"
                IsClippedToBounds="True"
                Text="1"
                TextColor="White">
                <Image IsOpaque="True" Source="Alerts.png" />
            </controls:BadgeView>
        </StackLayout>
    </StackLayout>`

image

Can it be due to the code in XamarinCommunityToolkit/Views/BadgeView/BadgeView.shared.cs at line 270 in the switch condition?

Another issue I have is that the badge breaks my layout when I added into a row in a ListView.
The DataTemplate is a ViewCell with a PancakeView
Layout without the Badge
image

With the BadgeView:

image

### Basic Information

- Version with issue: 1.0.0-preview1091
- Last known good version: 
- IDE: Visual Studio 2019 16.8.0 Preview 6.0
- Platform Target Frameworks:
  - iOS:  12
  - Android: 7.1

- Nuget Packages:
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.0.0-preview1091" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1560" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
    <PackageReference Include="Xamarin.Forms.Maps" Version="4.8.0.1560" />
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />

### PR DESCRIPTION
**Pull request by Rabosa616**
Fix the wrong assignation of margins when the text is assigned.

### Description of Change ###

There were no consistent margins between when the Badge was at the top positions or at the bottom as I showed in the first part of the issue #535. 

### Bugs Fixed ###

- Fixes #535 

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=552) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=552) before we can accept your contribution.<br/><br/>:x: Rabosa616 [sign now](https://cla.dotnetfoundation.org/xamarin/XamarinCommunityToolkit?pullRequest=552)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/XamarinCommunityToolkit?pullRequest=552) it.</sub>

**Comment by pictos** [comment]
@Rabosa616 can you verify your CLA status?

**Comment by Rabosa616** [comment]
image
I don't know why the @dnfadmin says that CLA is not signed if I go to site I see that is signed

image

**Comment by pictos** [comment]
@jfversluis, do you have any idea about this issue?

**Comment by jfversluis** [comment]
Hm it seems the GitHub checks thinks it's OK, so I guess all is in order. Maybe some kind of hiccup. Ignore it for now, we'll see what happens if you open a second PR :)

**Review by jsuarezruiz — APPROVED** [review]

**Review by AndreiMisiukevich — COMMENTED** [review]
LGTM

**Pull request merged**
