### PR TITLE
Initial Docs Setup

### PR DESCRIPTION
**Pull request by AlexHedley**
### Description of Change ###

This PR brings in a GitHub Pages hosted documentation site using [DocFX](https://dotnet.github.io/docfx/).

#121 has a discussion about possible solutions, this is just a temporary measure until the docs can be added to the official MS site like [Essentials](https://github.com/xamarin/Essentials/tree/develop/docs/en) but being that this is using the same technology it could mean minimal effort to transfer over but allows for proper documentation to be written whilst there is on-going development.

The workflow `yml` shows the Actions being used.

One manual step to make, if merged, is you need to toggle: 
Settings | **GitHub Pages** | Source to *master branch* then to *gh-pages branch* for the first build to trigger then subsequent pushes work fine.

You can see an example on my fork [here](https://alexhedley.github.io/XamarinCommunityToolkit/).

### CODE REVIEW

**Comment by jfversluis** [comment]
Awesome work @AlexHedley ! Thank you so much :D 

I'm not entirely familiar with GH Pages, and I think you mention it, but the branch switch is just once right?

**Comment by AlexHedley** [comment]
@jfversluis yes, just the once or it doesn’t trigger the initial release of the website unfortunately, but then new pushes will update fine

**Comment by SunnyMukherjee** [comment]
Hi @AlexHedley, I want to generate the docs for the Behaviors PR #126 so it is available whenever it is merged.  Can I follow the instructions on the DocFX site to generate the docs?  Or is there a better tutorial somewhere else?  Thanks.

**Comment by AlexHedley** [comment]
Hi @SunnyMukherjee 

The DocFX site is what I used to produce this,

I guess it depends, if this PR is completed first you could then pull that into yours.

If you create a new docs site in your branch you’d need to copy over this one to stop MCs and get all my config

You could add just a single markdown file with some Doco in it then when both are merged a maintainer could move it over, 

I’m not sure the best way to handle multiple forks atm

**Comment by jfversluis** [comment]
I would hold of on doing too much work here right now. As much as I appreciate the effort, we probably get more news about hosting our documentation on the Docs pages this week. Let’s wait for that a little to decide the right course of action and see if we can still use something from this PR

**Comment by SunnyMukherjee** [comment]
> Hi @SunnyMukherjee
> 
> The DocFX site is what I used to produce this,
> 
> I guess it depends, if this PR is completed first you could then pull that into yours.
> 
> If you create a new docs site in your branch you’d need to copy over this one to stop MCs and get all my config
> 
> You could add just a single markdown file with some Doco in it then when both are merged a maintainer could move it over,
> 
> I’m not sure the best way to handle multiple forks atm

I read through their site.  I thought it was a matter of adding their NuGet package and it would generate the documentation in a docs folder using the comments in our classes.  It sounds like what you have done in your PR and you are describing is different than what I understand.  I may have used DocFX or something similar a long time ago, but I guess I need to understand your approach to be on the same page.

**Comment by AlexHedley** [comment]
@SunnyMukherjee there’s two parts to the documentation.

One is the API side which is auto generated, just add good xml docs to your classes etc.

The other side it the hand written Articles which you write in Markdown i.e. example of how to use your behaviours with images, notes etc

**Comment by jfversluis** [comment]
I think all this moved to the Docs repo now, so we can close this here

**Pull request closed without merging**
