### PR TITLE
[Bug] Fixed CameraView Linker issue

### LINKED ISSUE #1443: CameraView issue - EventToCommandBehavior: Couldn't resolve the event
Hello there,
I'm using CameraView and EventToCommandBehavior to create some sort of a simple app that makes photos.
But I've faced with the issue of using EventToCommandBehavior. When running app in Release mode on both android emulator and real device I do see the following error in Application Output:

> [MonoDroid] UNHANDLED EXCEPTION:
> [MonoDroid] Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
> [MonoDroid]   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
> [MonoDroid] android.runtime.JavaProxyThrowable: System.ArgumentException: EventToCommandBehavior: Couldn't resolve the event.
> [MonoDroid] Parameter name: EventName

The code itself isn't that complicated:
 ```
<xct:CameraView
                x:Name="CameraView"
                BindingContext="{Binding CameraModel}"
                CameraOptions="{Binding CameraOption}"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand"
                CaptureMode="Photo">
                <xct:CameraView.Behaviors>
                    <xct:EventToCommandBehavior EventName="MediaCaptured" Command="{Binding CaptureCommand}" />
                </xct:CameraView.Behaviors>
</xct:CameraView>
```

The Environment is the latest one at this moment:

> Visual Studio Community 2019 for Mac
> Version 8.10.3 (build 15)
> Installation UUID: c4debf69-38dc-430a-b7ff-71b5f73fb9f3
> GTK+ 2.24.23 (Raleigh theme)
> Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
> 
> Package version: 612000140
> 
> Mono Framework MDK
> Runtime:
> Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
> Package version: 612000140
> 
> Roslyn (Language Service)
> 3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
> 
> NuGet
> Version: 5.9.0.7134
> 
> .NET Core SDK
> SDK: /usr/local/share/dotnet/sdk/5.0.301/Sdks
> SDK Versions:
> 	5.0.301

Thanks in advance for helping!!

### PR DESCRIPTION
**Pull request by GUOLDEV**
### Description of Change ###

Fixed CameraView Linker issue "EventToCommandBehaviour: Couldn't resolve the event."

I checked other XCT's Views and it seems the CameraView is the only one having this issue as other views don't have events or the event is used somewhere, so the Linker does not remove it.

CameraView events removed by the Linker:

- MediaCaptured
- MediaCaptureFailed

💡 We already use this approach in XCT, for example in `TabView.shared.cs`

### Bugs Fixed ###

- Fixes #1443  

### API Changes ###

Added PreserveAttribute:

`[Preserve(AllMembers = true)]`

<!-- List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`

Changed:

 - `object Cell.OldPropertyName` => `object Cell.NewPropertyName`
 
If there is an entirely new API, then you can use a more verbose style:

```csharp
public static class NewClass {
    public static int SomeProperty { get; set; }
    public static void SomeMethod(string value);
}
``` -->

### Behavioral Changes ###

<!-- Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase. -->

### PR Checklist ###
<!-- Please check all the things you did here and double-check that you got it all, or state why you didn't do something -->
- [x] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [ ] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard
<!-- If at all possible, please update/add the documentation on the repo below. We would very much appreciate that. If you are unable to, please consider at least opening an issue on the repo below so we know that Docs still need to be adjusted/created. Thanks! <3 -->
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by GUOLDEV** [comment]
@pictos @AndreiMisiukevich, I have fixed the reported issue based on the solution adopted across XCT, could you please have a look when you have a chance?

**Review by pictos — CHANGES_REQUESTED** [review]
@GUOLDEV thanks for the PR. Sadly this isn't the right solution for this case, we don't want to use the `AllMembers = true` because that prevent linker to remove those class, and we want this class to be removed if the user doesn't use the CameraView control. Said that you can try to add the `Condional = true` instead `AllMembers` and see if that works. If don't work we'll need to think in another solution.

**Comment by GUOLDEV** [comment]
@pictos I totally agree, so I have pushed the fix.

**Comment by pictos** [comment]
Thanks @GUOLDEV I'll test it locally ASAP

**Comment by jfversluis** [comment]
@pictos did you get a chance to test?

**Comment by pictos** [comment]
Not yet, I'll try to check out tomorrow during the afternoon.

**Review by pictos — APPROVED** [review]
Tested on my end and works as expected. Also, added a TestCase for this issue.

**Comment by GUOLDEV** [comment]
@pictos Thanks mate 🙏 Just one question, do you think there is a possible to have this fix included on the next preview release?

**Comment by pictos** [comment]
> @pictos Thanks mate 🙏 Just one question, do you think there is a possible to have this fix included on the next preview release 1.3.0 Preview 2?

For sure it's possible :D
Everything that is in develop will be on the next 1.3 release (preview or stable)

**Pull request merged**
