### PR TITLE
Bugfix/tabindicatorwidth

### PR DESCRIPTION
**Pull request by RonnyRos**
### Description of Change ###

My first PR.

Should fix the tabindicator resetting to default width, now it remembers the set tabindicator width set.
Should fix the tabindicator not following the selected tab, now follows the selected tab.

Tested on a Android emulator, should probably be tested more.

### Bugs Fixed ###
https://github.com/xamarin/XamarinCommunityToolkit/issues/947

### Description of Change ###

Should fix the tabindicator resetting to default width, now it remembers to set tabindicator width while navigating.
Should fix the tabindicator not following the selected tab. It now should follow the tab.

Tested only on a Android emulator, should probably be tested more.
Sample is in TabWidth view where indicatorwidth is set.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
Hey @RonnyRos something went wrong.
Did you want to submit a PR to develop branch instead?

**Comment by RonnyRos** [comment]
Yes i did, changed it now. Thank you.

**Comment by brminnick** [comment]
@RonnyRos Can you please enable Allow Edits From Maintainers? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

This PR is currently out-of-date with the `main` branch and we need to be able to click the "Update Branch" button to be unblocked from merging it.

**Review by brminnick — APPROVED** [review]
Thanks @RonnyRos!

**Pull request merged**
