### PR TITLE
[Converter] Combined Converters (main)

### LINKED ISSUE #553: [Enhancement] Converters modification
## Summary

There are converters which have return the value and the opposite value. They can be combined into 1 converter by using converter parameter.
e.g. IsNullOrEmptyConverter vs IsNotNullOrEmptyConverter. ListIsEmptyConverter vs ListIsNotEmptyConverter

## API Changes

1. remove *Not*Converters
2. use boolean parameters.

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

### PR DESCRIPTION
**Pull request by GUOLDEV**
Fixes #553 

Combined Converters IsNotNullOrEmptyConverter, ListIsNullOrEmptyConverter and ListIsNotNullOrEmptyConverter into IsNullOrEmptyConverter, implementing InvertCheck flag to invert the result.

If it is ok, IsNotNullOrEmptyConverter, ListIsNullOrEmptyConverter and ListIsNotNullOrEmptyConverter can be removed as all of them can be replaced using IsNullOrEmptyConverter with InvertCheck flag.

### Bugs Fixed ###

NA

### API Changes ###

<!-- List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`

Changed:

 - `object Cell.OldPropertyName` => `object Cell.NewPropertyName`
 
If there is an entirely new API, then you can use a more verbose style:

```csharp
public static class NewClass {
    public static int SomeProperty { get; set; }
    public static void SomeMethod(string value);
}
``` -->
Changed:

- IsNullOrEmptyConverter
- IsNotNullOrEmptyConverter
- ListIsNullOrEmptyConverter
- ListIsNotNullOrEmptyConverter

### Behavioral Changes ###

<!-- Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase. -->

NA

### PR Checklist ###
<!-- Please check all the things you did here and double-check that you got it all, or state why you didn't do something -->

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [ ] Changes adhere to coding standard
<!-- If at all possible, please update/add the documentation on the repo below. We would very much appreciate that. If you are unable to, please consider at least opening an issue on the repo below so we know that Docs still need to be adjusted/created. Thanks! <3 -->
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by Cfun1** [comment]
I think you should target develop branch since it a new feature.

**Comment by GUOLDEV** [comment]
@Cfun1 I will rebase it then.

**Comment by GUOLDEV** [comment]
@Cfun1 I have created a [PR](https://github.com/xamarin/XamarinCommunityToolkit/pull/1142) targeting develop branch.

**Comment by maxkoshevoi** [comment]
Could you close the PR please, since you created new one for develop branch?

**Pull request closed without merging**
