### PR TITLE
Fix DisplaySnackBarAsync Task never completes if another SnackBar appears, and completes before SnackBar action

### LINKED ISSUE #1340: [Bug] DisplaySnackBarAsync does not wait for action task
### Steps to Reproduce

Debug the following code, and tap on "Retry" button.
```csharp
            bool invoked = false;
            var result = await page.DisplaySnackBarAsync("test", "Retry", async () =>
             {
                 await Task.Delay(3000);
                 invoked = true;
                 // Breakpoint1
             });

            // Breakpoint2
```

### Expected Behavior
Retry action is awaited, Breakpoint2 is hit after Breakpoint1.

### Actual Behavior
Retry action is not awaited, Breakpoint1 is hit after Breakpoint2.

### Basic Information

- Version with issue: 1.1.0
- Platform Target Frameworks:
  - Android

### Workaround
I did something like that:
```csharp
            bool invoked = false;
            Task retryTask = null;
            var snackbarResult = await page.DisplaySnackBarAsync(text, "Retry", async () =>
            {
                async Task RetryAction()
                {
                    await Task.Delay(3000);
                    invoked = true;
                }
                retryTask = RetryAction();
                await retryTask;
            });

            if (snackbarResult)
            {
                await retryTask;
            }
```

### LINKED ISSUE #1341: [Bug] DisplaySnackBarAsync Task never completes if another SnackBar appears
### Steps to Reproduce

Execute the following:
```csharp
            var task1 = page.DisplaySnackBarAsync("Test1", "Action", () => Task.Delay(10));
            var task2 = page.DisplaySnackBarAsync("test2", "Action", () => Task.Delay(10));

            var res1 = await task1;
            var res2 = await task2;
```

### Expected Behavior
Both tasks are completed, res1 and res2 are false;

### Actual Behavior
task1 never completes, therefore execution is stuck.

### Basic Information

- Version with issue: 1.1.0
- Platform Target Frameworks:
  - Android

### PR DESCRIPTION
**Pull request by maxkoshevoi**
### Description of Change ###

- Set task result as `false` if SnackBar was closed via anything but executing an action.
- Wait until SnackBar action completion and pass exceptions from it into resulting task so they can be caught

**Issue**
There are 4 possible ways for SnackBar to be closed:
image

Current implementation handles only two (so task never completed for other two):
image

### Bugs Fixed ###

- Fixes #1341
- Fixes #1340

### API Changes ###

None

### Behavioral Changes ###

- SnackBar task always competes
- `DisplaySnackBarAsync` waits until SnackBar action completes
- Catching exceptions in `DisplaySnackBarAsync` also catches them in SnackBar action

### PR Checklist ###

- [x] Has a linked Issue, and the Issue has been `approved`
- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Review by VladislavAntonyuk — DISMISSED** [review]

**Comment by pictos** [comment]
@maxkoshevoi are you able to create tests for it inside our sample in the TestCases?

**Comment by maxkoshevoi** [comment]
@pictos Added tests

**Comment by maxkoshevoi** [comment]
@jfversluis @pictos Could you take another look at this, please?

**Review by pictos — DISMISSED** [review]

**Comment by brminnick** [comment]
> @Dreamescaper if I had rights, I would merge this PR

@VladislavAntonyuk Go for it! 

It looks like it needs one more Review + Approve then you can merge it. 

Give it a quick double-check to make sure everything still looks good, approve it, then merge it in!

**Review by VladislavAntonyuk — APPROVED** [review]

**Pull request merged**
