### PR TITLE
Fix badge view default text "0"

### LINKED ISSUE #1900: [Bug] The initial value of property couldn't display correctly on xct:BadgeView  when using data binding.
### Description

 The initial value of the binding property couldn't display correctly on `xct:BadgeView`  when using data binding. But after changing the value of the binding property, the UI could update correctly on  `xct:BadgeView`.

### Steps to Reproduce

1. create a  xamarin forms demo
2. copy the following code to this demo:
  
 ```
  public class MyViewModel: INotifyPropertyChanged 
    {
        public ICommand TestCommmand => new Command(TestMethod);

        private void TestMethod(object obj)
        {
            NotificationsNumber = 168;
        }

        private int _notificationsNumber = 0;

   
        public int NotificationsNumber
        {
            get => _notificationsNumber;
            set => SetProperty(ref _notificationsNumber, value);
        }

        public MyViewModel() {

            NotificationsNumber = 0;
        }

        bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)
        {
            if (Object.Equals(storage, value))

                return false;

            storage = value;

            OnPropertyChanged(propertyName);

            return true;

        }

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }

```

  **MainPage.xaml**

```
  <?xml version="1.0" encoding="utf-8" ?> 
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://xamarin.com/schemas/2020/toolkit" xmlns:formapp826="clr-namespace:FormApp826"
             x:Class="FormApp826.MainPage">

    <ContentPage.BindingContext>
        <formapp826:MyViewModel></formapp826:MyViewModel>
    </ContentPage.BindingContext>

    <StackLayout Padding="10">
        <Label  Text="{Binding NotificationsNumber}" HorizontalOptions="Center" FontSize="Header"   />

        <xct:BadgeView
            
            Margin="10"
            BackgroundColor="Red"
            FontAttributes="Bold"
            FontSize="Medium"
            TextColor="White"
            Text="{Binding NotificationsNumber}">
            <Label
                Text="This label has a badge in the top-right"/>
        </xct:BadgeView>


        <Button  Text="change value" Command="{Binding TestCommmand}"  />

    </StackLayout>

</ContentPage>
```

3.  deploy the app to a android device, the result is as follows:
   
     
image

  We could find that the first Label could   display `NotificationsNumber` correctly(`0`) ,but for the   `xct:BadgeView`  ,the value of `NotificationsNumber`  can not display correctly.

After that, we can try to click button `change value`,  here  we change  the value  of  `NotificationsNumber`, we can find that the value of `NotificationsNumber` could update correctly for both `label` and  `xct:BadgeView` .

image

### Expected Behavior

The initial value of property could display correctly on xct:BadgeView  when using data binding.

### Actual Behavior

The initial value of property couldn't display correctly on xct:BadgeView  when using data binding.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### PR DESCRIPTION
**Pull request by FedericoNembrini**
### Description of Bug ###
BadgeView default Text value is never set.

The Text property has a default value of 0, but it is never set to the actual label. This prevents the BadgeView from being displayed if it is bound to a property with a value of 0 and AutoHide is set to false.

### Issues Fixed ###

- Fixes #1900 

### PR Checklist ###

- [ ] Has a linked Issue, and the Issue has been `approved`
- [ ] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)

### CODE REVIEW

**Comment by FedericoNembrini** [comment]
@microsoft-github-policy-service agree

**Review by bijington — APPROVED** [review]
This looks good to me. I haven't had a chance to test with AutoHide set to true, did you manage to test and make sure that functionality still works?

**Comment by FedericoNembrini** [comment]
AutoHide default value is set to `true` 
https://github.com/xamarin/XamarinCommunityToolkit/blob/e7c0c80d79d363e949443970e7c65bcfd6717c57/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs#L54-L59

And `BadgeIndicatorContainer` visibility is set to `false`

https://github.com/xamarin/XamarinCommunityToolkit/blob/e7c0c80d79d363e949443970e7c65bcfd6717c57/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs#L286-L291

In my test case, the second label is wrapped in a BadgeView and AutoHide is true. When the binded text is changed it is always called `UpdateVisibilityAsync`.
https://github.com/xamarin/XamarinCommunityToolkit/blob/e7c0c80d79d363e949443970e7c65bcfd6717c57/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs#L199-L206

As a result, the default behaviour of AutoHide remains unchanged

**Comment by bijington** [comment]
@FedericoNembrini Thank you for this submission!

**Pull request merged**
