### PR TITLE
AnimationBehavior enhancements

### LINKED ISSUE #1175: [Enhancement] Provide ability to start Animations from a Command
## Summary

Provide the ability to start an Animation from something other than a View. Ideally I want to drive it when deciding whether a page is valid and the user is pressing the submit/save/create button.

## API Changes

Add `AnimateCommand` to `AnimationBehavior` which will be an `ICommand` with a `OneWayToSource` binding.

## Intended Use Case

Rather than disabling a Button based on whether there are validation errors on a Page. I would like to make the invalid controls shake to draw the users attention to the invalid controls. I believe this will serve a much wider set of use cases for being able to drive animations from within a ViewModel. See image below (apologies for my terrible touch screen based handwriting 😄 )

113418666-d5ccc180-93bd-11eb-8644-ec86ef9321e7

## Who Will Do The Work?

- [x] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up

### PR DESCRIPTION
**Pull request by bijington**
### Description of Change ###

Addition of `AnimateCommand` to the `AnimationBehavior` class which lets the animation be triggered from a read-only `Command`.

### Bugs Fixed ###

- Fixes #1175

### API Changes ###

<!-- List all API changes here (or just put None), example:

Added: 
 
- `string Class.Property { get; set; }`
- `void Class.Method();`

Changed:

 - `object Cell.OldPropertyName` => `object Cell.NewPropertyName`
 
If there is an entirely new API, then you can use a more verbose style:

```csharp
public static class NewClass {
    public static int SomeProperty { get; set; }
    public static void SomeMethod(string value);
}
``` -->

Added: 
 
- `ICommand AnimationBehavior.AnimateCommand { get; }`

### Behavioral Changes ###

<!-- Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase. -->

The `AnimationBehavior` class can have it's animation be triggered from a read-only `Command`.

### PR Checklist ###
<!-- Please check all the things you did here and double-check that you got it all, or state why you didn't do something -->
- [x] Has a linked Issue, and the Issue has been `approved`
- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR *I merged from xct/main into my main, is that good enough?*
- [x] Changes adhere to coding standard *I think so*
<!-- If at all possible, please update/add the documentation on the repo below. We would very much appreciate that. If you are unable to, please consider at least opening an issue on the repo below so we know that Docs still need to be adjusted/created. Thanks! <3 -->
- [ ] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit) *Not yet but I do intend to*

### CODE REVIEW

**Comment by pictos** [comment]
@bijington can you sign-in into the microsoft-cla ?

**Comment by pictos** [comment]
@bijington also, you should rebase your PR against the `develop` branch

**Comment by pictos** [comment]
> @pictos I have signed the Microsoft-cla, not sure why it isn't showing that I have.
> 
> Damn sorry about the `main` / `develop` mix up.

It's ok (:

**Comment by bijington** [comment]
I have tried rebasing locally but git is complaining about some merge conflicts with pipeline yaml files. I am tempted to close this PR and and just start the changes off develop again

**Comment by pictos** [comment]
> I have tried rebasing locally but git is complaining about some merge conflicts with pipeline yaml files. I am tempted to close this PR and and just start the changes off develop again

Go for it

**Comment by bijington** [comment]
Replaced by PR #1180 which is on the correct branch

**Pull request closed without merging**
