### PR TITLE
Implemented data-bindable Position property for MediaElement

### LINKED ISSUE #330: [Bug] MediaElement custom position bar is inelegant (paper cut)
### Description

Creating a custom position bar is currently a bit inelegant. All because you can't bind to the `Position` property (related issue: xamarin/Xamarin.Forms#9559).

I have a `PositionSlider` control, to represent a custom position bar. It exposes `Duration`, `Position`, and `TimeToEnd` properties. I use it as follows:

```
        <controls:PositionSlider x:Name="positionSlider"
                                 BindingContext="{x:Reference mediaElement}"
                                 Duration="{Binding Duration}"
                                 ValueChanged="OnPositionSliderValueChanged">
            <controls:PositionSlider.Triggers>
                <DataTrigger TargetType="controls:PositionSlider"
                             Binding="{Binding CurrentState}"
                             Value="{x:Static MediaElementState.Buffering}">
                    <Setter Property="IsEnabled" Value="False" />
                </DataTrigger>
            </controls:PositionSlider.Triggers>
        </controls:PositionSlider>
```

`PositionSlider.Duration` is bound to `MediaElement.Duration`. But you can't bind `PositionSlider.Position` to `MediaElement.Position` because `MediaElement.Position` deliberately doesn't send property change notifications at this time.

So you end up with the following mechanism:

1. Poll `MediaElement.Position` every X milliseconds to get the correct value and update the UI with its value.
1. Have an event handler for `PositionSlider.ValueChanged` that cancels the polling, updates `MediaElement.Position` from `PositionSlider.Position`, and then starts the polling again.

It'd be so much nicer if you could just accomplish this with data binding (so eliminating the `ValueChanged` event handler).

Sample: [WorkingWithMediaElement.zip](https://github.com/xamarin/Xamarin.Forms/files/4219501/WorkingWithMediaElement.zip)

### PR DESCRIPTION
**Pull request by peterfoot**
### Description of Change ###

Position property now regularly reports change events while media is playing. Uses internal timer and supports arbitrary seeking. Also added a TimeSpanToDoubleConverter to allow controls such as Slider which use a double value to be bound to the TimeSpan properties.

### Bugs Fixed ###

- Fixes #330 

### API Changes ###

MediaElement - None

Added:
Xamarin.CommunityToolkit.Converters.TimeSpanToDoubleConverter

### Behavioral Changes ###

Position property now reports value changes on an internal timer (200ms) to allow controls to be data-bound to the live value - e.g. slider control without having to implement a Timer and additional code.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [X] Has samples (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [X] Changes adhere to coding standard

Rebased on top of mediaelement branch because that contains the latest work on the control.

### CODE REVIEW

**Comment by pictos** [comment]
@peterfoot thanks for your contribution. Can you rebase your branch against the `MediaElement` branch? Your changes are unding all work done in #342

**Comment by jfversluis** [comment]
Whoa. Not sure why this got closed without merging. I _think_ the changes came in alright? @pictos @peterfoot could you please check what of your changes has gone into main and if everything seems in order?

**Comment by peterfoot** [comment]
@jfversluis nope, none of my changes made it. What happens now, do I start again against the main branch? 😢

**Comment by jfversluis** [comment]
Sorry about that! :( I guess whenever the target branch is merged it will automatically close open PRs against it.

If you would be willing and able to do that, that would be awesome <3

**Comment by peterfoot** [comment]
@jfversluis cool, I've created a new PR #381 against the main branch with the required changes.

**Pull request closed without merging**
