### PR TITLE
Create DelegateWeakEventManager

### LINKED ISSUE #293: [Enhancement] Leverage `Xamarin.Forms.WeakEventManager`
## Summary

If/when we increase the minimum Xamarin.Forms dependency to Xamarin.Forms v5.0, let's leverage `Xamarin.Forms.WeakEventManager`.

This PR adds `Xamarin.CommunityToolkit.Helpers.WeakEventManager`: https://github.com/xamarin/XamarinCommunityToolkit/pull/279

In Xamarin.Forms v5.0, `Xamarin.Forms.WeakEventManager` will be public: https://github.com/xamarin/Xamarin.Forms/pull/12063.

However, XamarinCommunityToolkit cannot currently leverage `Xamarin.Forms.WeakEventManager` because it has a dependency on Xamarin.Forms v4.5.

## API Changes

Mark `Xamarin.CommunityToolkit.Helpers.WeakEventManager` as obsolete: 

```csharp
[Obsolete("Use Xamarin.Forms.WeakEventManager")]
public class WeakEventManager
```

## Intended Use Case

This will ensure that we aren't duplicating code/features between Xamarin.Forms and XamarinComunityToolkit.

XamarinCommunityToolkit can continue to extend `Xamarin.Forms.WeakEventManager` (same it currently extends `Xamarin.CommunityToolkit.Helpers.WeakEventManager`), adding support for `EventHandler<T>`, `Action`, and `Action<T>` events.

### PR DESCRIPTION
**Pull request by brminnick**
### Description of Change ###

This Pull Request updates Xamarin.CommunityToolkit to support `Xamarin.Forms.WeakEventManager`

### Bugs Fixed ###

- Fixes #293 

### API Changes ###

Changed:

- `WeakEventManager` => `DelegateWeakEventManager`
  - `DelegateWeakEventManager` enables support for `Delegate` events
  - `Xamarin.Forms.WeakEventManager` only supports `EventHandler` events

Added:
```csharp
public static class WeakEventManagerExtensions
{
    public static void RaiseEvent(this Forms.WeakEventManager weakEventManager, object sender, object eventArgs, string eventName) => weakEventManager.HandleEvent(sender, eventArgs, eventName);
}
```

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of target-forms-5.0 at time of PR
- [x] Changes adhere to coding standard
- [x] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit)
  - [x] Link to Docs PR: https://github.com/MicrosoftDocs/xamarin-communitytoolkit/pull/30

### CODE REVIEW

**Comment by pictos** [comment]
@brminnick please hold on to this PR. Today we merged a huge PR that changes the folder structure of this project. So I need to replicate this change on the XF5.0 branch. Probably I'll reset that branch and do a `force push` so this can have a lot of conflicts.

**Comment by pictos** [comment]
@brminnick I updated the branch, and it's building as you can see here #598 , I think that you are good to go (:

**Comment by brminnick** [comment]
Thanks @pictos!

I've updated this PR to match the new folder structure on `target-forms-5.0` and resolved the merge conflicts 👍 

Should be good to go (pending your review, of course 😃)!

**Review by pictos — COMMENTED** [review]
@brminnick what's the difference between `DelegateWeakEventManager` and `WeakEventManager`? From the issue, `WeakEventManager` should be marked by the `Obsolete` attribute. To me, since we don't have a stable release, we can just remove the `WeakEventManager` implementation. Thoughts?

**Comment by brminnick** [comment]
When you say `WeakEventManager`, I'm not sure if you're referring to `Xamarin.Forms.WeakEventManager` or `Xamarin.CommunityToolkit.Helpers.WeakEventManager`.

I renamed `Xamarin.CommunityToolkit.Helpers.WeakEventManager` to `Xamarin.CommunityToolkit.Helpers.DelegateWeakEventManager` so that we don't have naming conflicts. Renaming it helps avoid the `Ambigious Reference` error:

image


### DelegateWeakEventManager
- Supports `event EventHandler`
- Supports `event Action`
- Supports `event Delegate`
- Better Exception handling

### Xamarin.Forms.WeakEventManager
- Supports `event EventHandler`
- Does **not** support `event Action `
- Does **not** support `event Delegate `
  - E.g. You cannot use `Xamarin.Forms.WeakEventManager` with `INotifyPropertyChanged` events
- Does not provide custom Exceptions

**Comment by pictos** [comment]
Amazing explanation, thank you for that! I'll approve this PR, to me it's good. And I let you decide what to do with `WeakReferenceManager` and when to do it. (:

Thanks again.

**Review by pictos — APPROVED** [review]

**Pull request merged**
