### PR TITLE
Code formating preference

### PR DESCRIPTION
**Pull request by Cfun1**
Enable prefer one statement if block, without braces suggestion.

### CODE REVIEW

**Review by pictos — APPROVED** [review]

**Comment by jfversluis** [comment]
Actually I do prefer brackets even for a single line https://stackoverflow.com/questions/359732/why-is-it-considered-a-bad-practice-to-omit-curly-braces

That is what this disables right?

**Comment by Cfun1** [comment]
@jfversluis I do too but it was motivated after my code has been revewed to remove brackets, I am fine to close it.

**Comment by jfversluis** [comment]
Who mentioned that? Then I'll discuss that :)

Thanks for paying attention and then also updating these rules!

**Comment by Cfun1** [comment]
@jfversluis https://github.com/xamarin/XamarinCommunityToolkit/pull/846#discussion_r574033996

**Pull request closed without merging**
