### PR TITLE
Move C# Markup Extensions from Forms to Toolkit

### PR DESCRIPTION
**Pull request by VincentH-Net**
### Description of Change ###

Move the full C# Markup functionality from the [Xamarin Forms CSharpForMarkup Part 2](https://github.com/xamarin/Xamarin.Forms/pull/11428) PR into the XCT
- With full git history from Forms repo
- Without experimental feature flags
- With working example app, ported from [Introducing C# Markup for Xamarin.Forms](https://devblogs.microsoft.com/xamarin/c-sharp-markup-for-xamarin-forms/)
- 100% Unit test coverage; all tests green.<br />Two tests signaling [Forms issue 12683](https://github.com/xamarin/Xamarin.Forms/issues/12683) will fail after that issue is fixed; how to fix the tests then is included in TODO comments
- As a separate NuGet package `Xamarin.CommunityToolkit.Markup` (with corresponding namespace), targeting Forms 5; no dependencies on other XCT package(s)

This XCT PR depends on [Forms PR 12623](https://github.com/xamarin/Xamarin.Forms/pull/12623); until this is available in a NuGet feed, this XCT PR downloads and unzips the NuGet packages of the Forms PR on the restore build target

### Bugs Fixed ###
- Fixes https://github.com/xamarin/XamarinCommunityToolkit/issues/499

### API Changes ###
Add API's documented in [PR 29](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/pull/29).

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Has samples (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Changes adhere to coding standard

- [X] Updated [documentation](https://github.com/MicrosoftDocs/xamarin-communitytoolkit) in [PR 29](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/pull/29)

### CODE REVIEW

**Comment by VincentH-Net** [comment]
@jfversluis can you help me get the `Xamarin.CommunityToolkit.Markup.UnitTests.csproj` results visible?

the unit tests run in CI e.g. [see log](https://dev.azure.com/xamarin/public/_build/results?buildId=29992&view=logs&j=7868e7c0-c859-51b7-c3be-08c48f6833d0&t=fb76b7ed-e4f5-522c-a151-eb3e57e0f1a4&l=43) but they are not listed in the [test overview](https://github.com/xamarin/XamarinCommunityToolkit/pull/522/checks?check_run_id=1356908080) and also not present in the [test results tab in Azure Devops](https://dev.azure.com/xamarin/public/_build/results?buildId=29992&view=ms.vss-test-web.build-test-results-tab)

**Comment by VincentH-Net** [comment]
@jfversluis is it possible to enable code coverage in CI?
Markup is at 100%
image

**Comment by jfversluis** [comment]
Looks like I can see them just fine? 

image

image

Note that for the [screen in AzDO](https://dev.azure.com/xamarin/public/_build/results?buildId=29992&view=ms.vss-test-web.build-test-results-tab) it filters automatically for only failed tests. If you disable that, they show up.

I'll have a look at the coverage.

**Comment by VincentH-Net** [comment]
@jfversluis 
> Looks like I can see them just fine?
Nope, those are only the Xamarin.CommunityToolkit.UnitTests.csproj tests.
The tests in Xamarin.CommunityToolkit.Markup.UnitTests.csproj are not included; try filtering on Passed and "Markup".

Once they are included you should see an additional 255 tests

**Comment by jfversluis** [comment]
You mean these?

image

**Comment by VincentH-Net** [comment]
> You mean these?

@jfversluis yes! User error - I saw the top tests listed like this:
image

So I assumed my tests would also include the full namespace and I filtered on "Markup"
But for some reason my tests are shown like this:
image
(probably some NUnit default - I saw you use XUnit)

So that's why I never saw a result. 1055 is the correct total nr of tests

**Comment by jfversluis** [comment]
Yeah I agree, would be great if we can align that and get a bit better naming/categorising, etc. but something for later :)

**Comment by jfversluis** [comment]
If you pull in the change from #524 coverage is enabled too

**Comment by VincentH-Net** [comment]
> If you pull in the change from #524 coverage is enabled too

@jfversluis merged; works. Thanks! Results:

image

Not counting tests, C# Markup is just 13% of total XCT blocks. XCT is bigger than I thought 👍

**Comment by jfversluis** [comment]
Can we switch this one to [pre4](https://www.nuget.org/packages/Xamarin.Forms/5.0.0.1709-pre4) that should have all the bits? Then it's good to go afaic :)

**Comment by VincentH-Net** [comment]
> Can we switch this one to [pre4](https://www.nuget.org/packages/Xamarin.Forms/5.0.0.1709-pre4) that should have all the bits? Then it's good to go afaic :)

@jfversluis Done. Markup package version 1.0.0-pre4. All tests green; sample updated and tested; all works on Android, UWP and iOS.

Minor visual issue in the sample on iOS : the like button does not display - possibly a forms 5 issue; it uses `FontImageSource.GlyphProperty`  with characters "\u2764" and "\u2661". Will look into that later but for now this can be released, assuming that the Markup package and build settings for public release are OK (I copied those from the main XCT package but can't verify them for myself)

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
The version of the package will be overriden at the time of release, but we'll figure that out also in light of #529

**Pull request merged**
